### PR TITLE
fix: avoid double lock in DockerProvider.DaemonHost()

### LINKED ISSUE #2897: [Bug]: deadlock in container.Host()
### Testcontainers version

v0.34.1-0.20241126184225-db433916fa6a

### Using the latest Testcontainers version?

Yes

### Host OS

linux

### Host arch

x86

### Go version

go version go1.23.3 linux/amd64

### Docker version

```shell
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:17 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx

Server:
 Containers: 21
  Running: 20
  Paused: 0
  Stopped: 1
 Images: 396
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dd1e886e55dd695541fdcd67420c2888645a495
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.112+
 Operating System: Debian GNU/Linux 11 (bullseye) (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.35GiB
 Name: viktor-main
 ID: 74745a36-d417-4e03-89f2-52e442230a26
 Docker Root Dir: /home/.docker_data
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

deadlock calling `container.Host()` from a test running in a container

### Relevant log output

```shell
Stacktrace:

goroutine 7 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x412e98?, 0x68?, 0x1?)
        /usr/local/go/src/runtime/sema.go:95 +0x25
sync.(*Mutex).lockSlow(0xc00011a410)
        /usr/local/go/src/sync/mutex.go:173 +0x15d
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:92
github.com/testcontainers/testcontainers-go.(*DockerProvider).ensureDefaultNetwork(0xc00011a370, {0x9dbaa0, 0xc000142fc0})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/docker.go:1625 +0x8a
github.com/testcontainers/testcontainers-go.(*DockerProvider).GetGatewayIP(0xc00011a370, {0x9dbaa0, 0xc000142fc0})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/docker.go:1597 +0x3a
github.com/testcontainers/testcontainers-go.(*DockerProvider).daemonHostLocked(0xc00011a370, {0x9dbaa0, 0xc000142fc0})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/docker.go:1501 +0x205
github.com/testcontainers/testcontainers-go.(*DockerProvider).DaemonHost(0xcb1a20?, {0x9dbaa0?, 0xc000142fc0?})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/docker.go:1475 +0xc5
github.com/testcontainers/testcontainers-go.(*DockerContainer).Host(0x9db9f8?, {0x9dbaa0?, 0xc000142fc0?})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/docker.go:165 +0x25
github.com/testcontainers/testcontainers-go/wait.(*HostPortStrategy).WaitUntilReady(0xc00039ecc0, {0x9db9f8?, 0xc00011d3e0?}, {0x9ddad8, 0xc00017a0e0})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/wait/host_port.go:107 +0xbe
github.com/testcontainers/testcontainers-go.init.func3.2({0x9db9f8, 0xc00011d3e0}, {0x9e0230, 0xc00017a0e0})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/lifecycle.go:289 +0x1a9
github.com/testcontainers/testcontainers-go.(*DockerContainer).applyLifecycleHooks.containerHookFn.func1({0x9e0230, 0xc00017a0e0})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/lifecycle.go:472 +0xd6
github.com/testcontainers/testcontainers-go.(*DockerContainer).applyLifecycleHooks(0xc00017a0e0, {0x9db9f8, 0xc00011d3e0}, 0x1, 0x9587b8)
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/lifecycle.go:413 +0x1fe
github.com/testcontainers/testcontainers-go.(*DockerContainer).startedHook(...)
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/lifecycle.go:351
github.com/testcontainers/testcontainers-go.(*DockerContainer).Start(0xc00017a0e0, {0x9db9f8, 0xc00011d3e0})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/docker.go:237 +0x189
github.com/testcontainers/testcontainers-go.(*DockerProvider).RunContainer(_, {_, _}, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/docker.go:1448 +0x95
github.com/testcontainers/testcontainers-go.(*reaperSpawner).newReaper(0xcb01d0, {0x9db9f8, 0xc00011d3e0}, {0xc0001e4f00, 0x40}, {0x9d96f8, 0xc00011a370})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/reaper.go:419 +0x74b
github.com/testcontainers/testcontainers-go.(*reaperSpawner).reuseOrCreate(0xcb01d0, {0x9db9f8, 0xc00011d3e0}, {0xc0001e4f00, 0x40}, {0x9d96f8, 0xc00011a370})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/reaper.go:329 +0x16c
github.com/testcontainers/testcontainers-go.(*reaperSpawner).reaper.(*reaperSpawner).retryLocked.func1()
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/reaper.go:281 +0x68
github.com/cenkalti/backoff/v4.doRetryNotify[...](0xc000414ef0?, {0x7c8025b4a0d8, 0xc00013c5a0}, 0x0, {0x0, 0x0?})
        /go/pkg/mod/github.com/cenkalti/backoff/v4@v4.3.0/retry.go:88 +0x12b
github.com/cenkalti/backoff/v4.RetryNotifyWithData[...](...)
        /go/pkg/mod/github.com/cenkalti/backoff/v4@v4.3.0/retry.go:54
github.com/cenkalti/backoff/v4.RetryWithData[...](0x899380?, {0x7c8025b4a0d8?, 0xc00013c5a0?})
        /go/pkg/mod/github.com/cenkalti/backoff/v4@v4.3.0/retry.go:43 +0x2b
github.com/testcontainers/testcontainers-go.(*reaperSpawner).reaper(0xcb01d0, {0x9db9f8, 0xc00011d3e0}, {0xc0001e4f00, 0x40}, {0x9d96f8, 0xc00011a370})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/reaper.go:270 +0x2fe
github.com/testcontainers/testcontainers-go.(*DockerContainer).connectReaper(0xc00017a000, {0x9db950, 0xcd31e0})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/docker.go:898 +0x118
github.com/testcontainers/testcontainers-go.(*DockerProvider).CreateContainer(_, {_, _}, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/docker.go:1250 +0x18ec
github.com/testcontainers/testcontainers-go.GenericContainer({_, _}, {{{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}, ...})
        /go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.34.1-0.20241126184225-db433916fa6a/generic.go:74 +0x308
<redacted>
```

### Additional information

```go
package settlementnetwork

import (
	"context"
	"testing"

	"github.com/testcontainers/testcontainers-go"
)

func TestBlah(t *testing.T) {
	req := testcontainers.ContainerRequest{
		Name:  "example",
		Image: "alpine",
	}
	container, err := testcontainers.GenericContainer(context.Background(), testcontainers.GenericContainerRequest{
		ContainerRequest: req,
		Started:          true,
	})
	if err != nil {
		t.Fatal(err)
	}
	container.Host(context.Background())
}

```

To repro, run the test in a container:
```
docker run --rm -it -w $(pwd) -v $(pwd):$(pwd) -v /var/run:/var/run golang
```

### PR DESCRIPTION
**Pull request by vikstrous**
## What does this PR do?

I carved out a code path for the DockerProvider.DaemonHost() code that avoids double locking.

## Why is it important?

I was getting a deadlock. See #2897

## Related issues

- Closes #2897

## How to test this PR

See #2897

## Follow-ups

Is there a test for running testcontainers from within a container?

### CODE REVIEW

**Review by stevenh — CHANGES_REQUESTED** [review]
Thanks for the PR @vikstrous nice catch.

Could I ask you to take a different approach, splitting `ensureDefaultNetwork` into two `ensureDefaultNetwork` and `ensureDefaultNetworkLocked` avoiding the need to pass a boolean and making it clear the intent of the calls to the locked method.

Could you also construct a test which exercises this issue to ensure we don't have regression.

File: docker.go [hunk 1]
```diff
@@ -1593,12 +1597,14 @@ func (p *DockerProvider) GetNetwork(ctx context.Context, req NetworkRequest) (ne
...
 func (p *DockerProvider) GetGatewayIP(ctx context.Context) (string, error) {
-	// Use a default network as defined in the DockerProvider
 	defaultNetwork, err := p.ensureDefaultNetwork(ctx)
 	if err != nil {
 		return "", fmt.Errorf("ensure default network: %w", err)
 	}
+	return p.getGatewayIP(ctx, defaultNetwork)
+}
 
+func (p *DockerProvider) getGatewayIP(ctx context.Context, defaultNetwork string) (string, error) {
```
Comment (vikstrous) [inline docker.go:1607]: By making defaultNetwork a parameter, I was able to move the decision about whether or not to lock to the caller. This function doesn't need to decide anything about locking any more.

**Comment by vikstrous** [comment]
@stevenh are there existing tests where testcontainers code is being run in containers (testcontainers?)?

**Comment by vikstrous** [comment]
I added a regression test. Without my change, the test fails and shows the stack trace you'd expect. With my change, it passes. The test runs in about 20s because it has to re-download go mod dependencies within the test container. This test can obviously be written a lot better, but I'd prefer it if you guys take over from here and make it conform to your best practices for writing tests.

File: docker.go (hunk 1 above)
Comment (stevenh) [reply docker.go:1608]: I should mention that default network will soon be removed in by the context rework that's currently in progress.

File: docker_test.go [hunk 2]
```diff
@@ -46,6 +49,62 @@ func init() {
...
+	})
+	require.NoError(t, err)
+	// The timeout is necessary because when TestWithinContainersStage2 fails, it hangs forever instead of erroring
+	exitCode, outputReader, err := container.Exec(context.Background(), []string{"go", "test", "-v", "-run", "^TestWithinContainerStage2$", "-timeout", "10s"}, exec.Multiplexed())
+	require.NoError(t, err)
+
+	outputStr, err := io.ReadAll(outputReader)
+	if err != nil {
+		t.Fatalf("failed to read output: %s", err)
+	}
```
Comment (stevenh) [inline docker_test.go:86]: suggestion: use require.NoError
```suggestion
	require.NoError(t, err)
```

File: docker_test.go [hunk 3]
```diff
@@ -46,6 +49,62 @@ func init() {
...
+	t.Logf("%s", outputStr)
+
+	if exitCode != 0 {
+		t.Fatalf("exit code %d, output: %s", exitCode, outputStr)
+	}
```
Comment (stevenh) [inline docker_test.go:91]: suggestion: use require.Zero
```suggestion
	require.Zerof(t, exitCode, "output: %s", outputStr)
```

File: docker_test.go [hunk 4]
```diff
@@ -46,6 +49,62 @@ func init() {
 	}
 }
 
+func TestWithinContainerStage1(t *testing.T) {
+	if providerType != ProviderDocker {
```
Comment (stevenh) [inline docker_test.go:53]: suggestion: add a todo as this distinction will be removed by the context work
```suggestion
	// TODO: remove this skip check when context rework is merged.        
	if providerType != ProviderDocker {
```

File: docker_test.go [hunk 5]
```diff
@@ -46,6 +49,62 @@ func init() {
...
+	}
+	t.Logf("%s", outputStr)
+
+	if exitCode != 0 {
+		t.Fatalf("exit code %d, output: %s", exitCode, outputStr)
+	}
+}
+
+// Regression test for deadlock #2897
+func TestWithinContainerStage2(t *testing.T) {
```
Comment (stevenh) [inline docker_test.go:95]: question: should this be skipped unless requested explicitly?

**Review by stevenh — CHANGES_REQUESTED** [review]
Thanks for the rework, have suggested a few changes and a question.

File: docker_test.go (hunk 5 above)
Comment (vikstrous) [reply docker_test.go:95]: Good point. What's the best way to do this? I'll try a command line flag.

Comment (stevenh) [reply docker_test.go:95]: The common way to do this is by setting and checking an environment variable

File: docker_test.go [hunk 6]
```diff
@@ -46,6 +50,65 @@ func init() {
...
+		Started:          true,
+	})
+	require.NoError(t, err)
+	// The timeout is necessary because when TestWithinContainersStage2 fails, it hangs forever instead of erroring
+	exitCode, outputReader, err := container.Exec(context.Background(), []string{"go", "test", "-v", "-run", "^TestWithinContainerStage2$", "-timeout", "20s", "-stage2"}, exec.Multiplexed())
+	require.NoError(t, err)
+
+	outputBytes, err := io.ReadAll(outputReader)
+	require.NoError(t, err, "failed to read output")
+	t.Logf("%s", outputBytes)
```
Comment (stevenh) [inline docker_test.go:87]: question: looks like this was just debug?

Comment (vikstrous) [reply docker_test.go:87]: Without this, you can't see the output of stage 2, so you don't really know if it's working. I'll remove the extra print in case of error though.

Comment (stevenh) [reply docker_test.go:87]: Ahh, got you because it's basically a sub test

**Review by stevenh — APPROVED** [review]

**Review by stevenh — CHANGES_REQUESTED** [review]
Unfortunately the test is failing in rootless setup, see CI output.

**Comment by vikstrous** [comment]
I got the same error locally when I didn't bind mount /var/run. I shared the docker socket with stage 2 by bind mounting /var/run from stage 1. I don't know how this works in your CI environment / with rootless docker. I'm basically just trying to make sure that stage 2 thinks it's in a container.

I'll need help with this part.

File: docker_test.go [hunk 7]
```diff
@@ -46,6 +50,65 @@ func init() {
...
+				Source: dir,
+				Target: dir,
+			}, mount.Mount{
+				Type:   "bind",
+				Source: "/var/run",
+				Target: "/var/run",
+			})
+		},
+		Entrypoint: []string{"sleep", "100"},
+	}
```
Comment (mdelapenya) [inline docker_test.go:75]: If what we want to do is run this in container in rootless mode, we'd need to set up the environment for that. You can find the rootless paths in the [docker_rootless.go:L35:39](https://github.com/testcontainers/testcontainers-go/blob/main/internal/core/docker_rootless.go#L35-L39):

> //  1. XDG_RUNTIME_DIR environment variable.
> //  2. ~/.docker/run/docker.sock file.
> //  3. ~/.docker/desktop/docker.sock file.
> //  4. /run/user/${uid}/docker.sock file.
> //  5. Else, return ErrRootlessDockerNotFound, wrapping secific errors for each of the above paths.

If you need to run this test in both modes, you probably need to configure the image accordingly. Please see https://github.com/testcontainers/testcontainers-go/blob/main/docker_test.go#L1546-L1548 as an example

```go
if os.Getenv("XDG_RUNTIME_DIR") != "" {
	t.Skip("Rootless Docker does not support setting rlimit")
}
```

Comment (vikstrous) [reply docker_test.go]: I pushed an attempt to fix the test, but you'll have to approve the CI run to find out if it worked. Feel free to take over my PR from here to fix the docker socket mounting issue if it's easier. If this doesn't work, it might be necessary to pass into the container XDG_RUNTIME_DIR.

Comment (vikstrous) [reply docker_test.go]: I pushed one last attempt to fix the test. Please take over from here if it doesn't work.

**Comment by vikstrous** [comment]
I think the rootless test is actually finding another version of this bug

**Comment by vikstrous** [comment]
Actually, I don't really know what's going on. I've never used rootless docker before and I think it would be best for someone to take over this PR. The bug makes testcontainers unusable within containers, which is a common scenario, so I want to get it fixed soon.

**Comment by stevenh** [comment]
Just a quick note to say this on my list thank @vikstrous just need to find some time, appreciate your time on this 😄

**Comment by vikstrous** [comment]
Niece improvement! Much simpler than actually running in a container.

**Review by mdelapenya — APPROVED** [review]
LGTM, thank you both for your time here 🙇
