### PR TITLE
fix(cockroachdb): Fixes cockroachdb wait strategy handling

### LINKED ISSUE #2453: [Bug]: CockroachDB module does not support overriding of wait strategy deadline
### Testcontainers version

0.29.1

### Using the latest Testcontainers version?

Yes

### Host OS

MacOS

### Host arch

ARM

### Go version

1.21

### Docker version

```shell
Client:
 Cloud integration: v1.0.35+desktop.11
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:26 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.28.0 (139021)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:22 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Version:    25.0.3
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/ahsiddiqui/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.6-desktop.1
    Path:     /Users/ahsiddiqui/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     /Users/ahsiddiqui/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/ahsiddiqui/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.22
    Path:     /Users/ahsiddiqui/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/ahsiddiqui/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.1
    Path:     /Users/ahsiddiqui/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/ahsiddiqui/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.5.0
    Path:     /Users/ahsiddiqui/.docker/cli-plugins/docker-scout
WARNING: Plugin "/Users/ahsiddiqui/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/ahsiddiqui/.docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 28
  Running: 0
  Paused: 0
  Stopped: 28
 Images: 30
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 7.657GiB
 Name: docker-desktop
 ID: 88a7eee7-be09-47a6-b30e-27e0bd44854d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  sv2lxcad03.corp.equinix.com:7100
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### What happened?

My tests have been failing in my CI pipeline because it takes more than a minute to start the cockroachdb test container. I wanted to increase the wait strategy's deadline time so the tests had a chance to run the container before the test failed. I looked at the documentation and [found something that mentioned that you could use the `WithWaitStrategyAndDeadline` method to specify a deadline](https://golang.testcontainers.org/modules/cockroachdb/#wait-strategies).

I tried doing this, but it didn't really work:
```
	cdbContainer, err := cockroachdb.RunContainer(
		ctx,
		testcontainers.WithImage("cockroachdb/cockroach:v23.2.1"),
		testcontainers.WithWaitStrategyAndDeadline(time.Minute*5, wait.ForHealthCheck()),
	)
```

I tried the same thing with Kafka container and it was successful in overriding the deadline:

```
	kafkaContainer, err := tcKafka.RunContainer(
		ctx,
		tcKafka.WithClusterID("test-kafka-cluster"),
		testcontainers.WithImage("confluentinc/cp-kafka:latest"),
		testcontainers.WithWaitStrategyAndDeadline(time.Minute*5, wait.ForHealthCheck()),
	)
```

### Relevant log output

```shell
log output for cockroachdb container running:
2024/03/28 18:38:11 🐳 Creating container for image cockroachdb/cockroach:v23.2.1
2024/03/28 18:38:11 ✅ Container created: 78dfd556e6fb
2024/03/28 18:38:11 🐳 Starting container: 78dfd556e6fb
2024/03/28 18:38:11 ✅ Container started: 78dfd556e6fb
2024/03/28 18:38:11 🚧 Waiting for container id 78dfd556e6fb image: cockroachdb/cockroach:v23.2.1. Waiting for: &{timeout:<nil> deadline:<nil> Strategies:[0x14000598100 0x140000461e0]}


----------------------------------------

log output for kafka container running:
2024/03/28 18:36:05 🐳 Creating container for image confluentinc/cp-kafka:latest
2024/03/28 18:36:05 ✅ Container created: 0212fc36d765
2024/03/28 18:36:05 🐳 Starting container: 0212fc36d765
2024/03/28 18:36:09 ✅ Container started: 0212fc36d765
2024/03/28 18:36:09 🚧 Waiting for container id 0212fc36d765 image: confluentinc/cp-kafka:latest. Waiting for: &{timeout:<nil> deadline:0x140004fe778 Strategies:[0x140000459b0]}
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bearrito**
## What does this PR do?
Fixes wait strategy handling. Previously cockroachdb was overwriting wait strategies.

## Why is it important?
Custom wait strategies were not being respected

## Related issues

- Closes #2453

## How to test this PR
I added tests.
There looks to be some form of connection logic in the `SQL` strategy. This has to be merged into the user provided strategy otherwise you will timeout.

### CODE REVIEW

File: modules/cockroachdb/cockroachdb_test.go [hunk 1]
```diff
@@ -144,6 +147,71 @@ func (suite *AuthNSuite) TestQuery() {
...
+		ctx := context.Background()
+
+		// This will succeed
+		suite.opts = append(suite.opts, testcontainers.WithWaitStrategyAndDeadline(time.Second*60, wait.ForLog(nodeStartUpCompleted)))
+		container, err := cockroachdb.RunContainer(ctx, suite.opts...)
+		suite.Require().NoError(err)
+
+		conn, err := conn(ctx, container)
+		suite.Require().NoError(err)
+		defer conn.Close(ctx)
```
Comment (AhmedNSidd) [inline modules/cockroachdb/cockroachdb_test.go:200]: Why no error checking to see if db connection was closed successfully?

File: modules/cockroachdb/cockroachdb_test.go [hunk 2]
```diff
@@ -144,6 +147,71 @@ func (suite *AuthNSuite) TestQuery() {
...
+		_, err = conn.Exec(ctx, "CREATE TABLE test (id INT PRIMARY KEY)")
+		suite.Require().NoError(err)
+		suite.T().Cleanup(func() {
+			if container != nil {
+				err := container.Terminate(ctx)
+				suite.Require().NoError(err)
+			}
+		})
+
+	})
```
Comment (AhmedNSidd) [inline modules/cockroachdb/cockroachdb_test.go:211]: I notice that there is inconsistency between how we are closing the db connection ("defer") and how we are terminating the container (using the cleanup functionality). Is there a reason for this? Can't we just use one?

File: modules/cockroachdb/cockroachdb.go [hunk 3]
```diff
@@ -186,6 +186,12 @@ func addWaitingFor(req *testcontainers.GenericContainerRequest, opts options) er
 		}),
 	)
 
+	if req.WaitingFor == nil {
+		req.WaitingFor = defaultStrategy
+	} else {
+		req.WaitingFor = wait.ForAll(req.WaitingFor, defaultStrategy)
```
Comment (AhmedNSidd) [inline modules/cockroachdb/cockroachdb.go:192]: Let's say that someone specified a waiting strategy of `wait.ForHTTP("/health").WithPort(defaultAdminPort),` similar to the default strategy, but this time they added a timeout. Would it override the default strategy here?

File: modules/cockroachdb/cockroachdb_test.go (hunk 1 above)
Comment (bearrito) [reply modules/cockroachdb/cockroachdb_test.go:200]: Defer is going to run at the end of scope, you aren't able to do this.

File: modules/cockroachdb/cockroachdb_test.go (hunk 2 above)
Comment (bearrito) [reply modules/cockroachdb/cockroachdb_test.go:211]: I'm not the original maintainer of this. This is what the tests were doing previously, it's also whats done project wide. See for example - https://github.com/testcontainers/testcontainers-go/blob/main/modules/postgres/postgres_test.go

File: modules/cockroachdb/cockroachdb.go (hunk 3 above)
Comment (bearrito) [reply modules/cockroachdb/cockroachdb.go:192]: It would get merged in meaning duplicate waits on the `wait.ForHTTP("/health")`

I agree this is cumbersome. I think what could be done is to pull the `wait.ForSQL` and then merge that into whatever the user is providing, this would get rid of the duplicate 

Overall it seems a bit awkward that connection logic is built into the wait for logic. Best approach might be to just separate that piece out entirely, however, I suspect there is some reason to keep it here though as the original author had some reason.

Comment (bearrito) [reply modules/cockroachdb/cockroachdb.go]: @AhmedNSidd I separated out this connection logic and added a test based on your comment.

**Review by mdelapenya — APPROVED** [review]
LGTM thank you for taking the time to fix this!

@bearrito I added a few minor comments regarding consistency around blank lines as separation for different code blocks, so once they are addressed, this is ready to be merged.

🚀

File: modules/cockroachdb/cockroachdb_test.go (hunk 1 above)
Comment (AhmedNSidd) [reply modules/cockroachdb/cockroachdb_test.go:197]: That's true, but you could defer (and run) an anonymous function, and in that anonymous function, you could close the database and then error check to see if it closed right.

That said, I'm not asking this change be made, especially if the rest of the tests aren't doing it like this. Was just curious because I'm new-ish to Golang so I am trying to understand best practices.

Feel free to resolve this thread.

Comment (mdelapenya) [reply modules/cockroachdb/cockroachdb_test.go:197]: Indeed, t.Cleanup could be of interest. Thanks @AhmedNSidd fro bringing this point to the table.

**Review by mdelapenya — DISMISSED** [review]
LGTM, there are a few non-blocking cosmetic comments here, but I think the PR can be merged if everybody agree.

I'll wait for you @bearrito and @AhmedNSidd for the open discussions, so at the moment they are closed, I'll merge this one.

Thank you both for your patience and for contributing to testcontainers-go!

**Review by AhmedNSidd — APPROVED** [review]
Changes look good to me. Please feel free to merge this one in @mdelapenya 

My pleasure re: contributing to `testcontainers-go` :) 
Thank you for maintaining this library.

File: modules/cockroachdb/cockroachdb.go [hunk 4]
```diff
@@ -167,25 +167,32 @@ func addWaitingFor(req *testcontainers.GenericContainerRequest, opts options) er
...
-
-			return stdlib.RegisterConnConfig(connCfg)
-		}),
+		sqlWait,
 	)
 
+	if req.WaitingFor == nil {
+		req.WaitingFor = defaultStrategy
+	} else {
+		req.WaitingFor = wait.ForAll(req.WaitingFor, sqlWait)
```
[the remark this answers is not in the document]
Comment (bearrito) [reply modules/cockroachdb/cockroachdb.go:193]: Are you suggesting we do this ?

```


defaultStrategy := wait.ForSQL( ... elided ...)
	

	if req.WaitingFor == nil {
		req.WaitingFor = wait.ForAll(wait.ForHTTP("/health").WithPort(defaultAdminPort),defaultStrategy)
	} else {
		req.WaitingFor = wait.ForAll(req.WaitingFor, defaultStrategy)
	}
```

I think you end up with the same thing.

Case 1: No Waiting for defined -> You get HTTP and SQL Waits
Case 2: A Wait is defined -> You get whatever the user passes in and SQL.

If that approach reads better I'm good with it.

[the remark this answers is not in the document]
Comment (bearrito) [reply modules/cockroachdb/cockroachdb.go:193]: Also, I can look in the source, but I might as well ask is `wait.ForAll` linear-ish eg if is FIFO or LIFO or in parallel ?

[the remark this answers is not in the document]
Comment (mdelapenya) [reply modules/cockroachdb/cockroachdb.go:193]: They are not run in parallel, so FIFO

[the remark this answers is not in the document]
Comment (mdelapenya) [reply modules/cockroachdb/cockroachdb.go:193]: > Case 2: A Wait is defined -> You get whatever the user passes in and SQL.

That's exactly my point: we lose here the original waitFor.HTTP, right? Is this intended?

[the remark this answers is not in the document]
Comment (bearrito) [reply modules/cockroachdb/cockroachdb.go:193]: That's what I originally had, but removed it. I have no problem switching it back.

Two arguments for/against:
1. If as a user I pass in a wait strategy I would expect that wait strategy to be exclusively used. However, the SQL is different as it has to be awaited for connection functionality.
2. Alternatively, we should always wait  with predetermined strategies until we have a usable container to provide the user. But then why allow the user to override at all?

It almost seems like what would be better would something like

```
 testcontainers.WithDeadline(time.Millisecond*20))
 ```
Where we could just add the deadline to the existing wait strategy (assuming it exists).

WDYT?

**Comment by bearrito** [comment]
@mdelapenya Is this good to go, the last failing test were unrelated

File: modules/cockroachdb/cockroachdb.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (mdelapenya) [reply modules/cockroachdb/cockroachdb.go:193]: Hey @bearrito sorry for the radio silence, May was a month in which I combined PTO and full-focus on an eventual v1 release of testcontainers-go. My apologies.

The wait.ForAll strategy comes with a deadline to be applied to all its children, so you could leverage that.

**Comment by bearrito** [comment]
@mdelapenya I reverted to always honor the default strategy. I don't think can do much more with cockroach, namely because how it's doing it's own thing with the `addWaitingFor` and `addingEnvs`

**Review by mdelapenya — APPROVED** [review]
LGTM, thanks!
