### PR TITLE
fix: mongodb replicaset should work with auth

### LINKED ISSUE #2755: [Bug]: Error when using WithUsername and WithPassword with the WithReplicaSet option
### Testcontainers version

v0.33.0

### Using the latest Testcontainers version?

Yes

### Host OS

MacOS

### Host arch

ARM

### Go version

1.23.0

### Docker version

```shell
Client:
 Cloud integration: v1.0.35+desktop.13
 Version:           26.0.0
 API version:       1.45
 Go version:        go1.21.8
 Git commit:        2ae903e
 Built:             Wed Mar 20 15:14:46 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.29.0 (145265)
 Engine:
  Version:          26.0.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       8b79278
  Built:            Wed Mar 20 15:18:02 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Version:    26.0.0
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.1-desktop.1
    Path:     /Users/chriss/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.26.1-desktop.1
    Path:     /Users/chriss/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.27
    Path:     /Users/chriss/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /Users/chriss/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.23
    Path:     /Users/chriss/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/chriss/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.1.0
    Path:     /Users/chriss/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/chriss/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.6.3
    Path:     /Users/chriss/.docker/cli-plugins/docker-scout

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 22
 Server Version: 26.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.22-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 12
 Total Memory: 7.657GiB
 Name: docker-desktop
 ID: 7b791e9f-a4a6-4582-94dd-1d6571714207
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///Users/chriss/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### What happened?

When running the following code, I consistently receive the error message stated in the log output.  I tried different mongo versions and with/without wait strategies and it's the same result.

`mongo, err := mongodb.Run(ctx, "mongo:latest",
		mongodb.WithReplicaSet("rs0"),
		mongodb.WithUsername("root"),
		mongodb.WithPassword("example"),
		testcontainers.WithWaitStrategy(wait.ForLog("Waiting for connections")),
	)` 

### Relevant log output

```shell
failed to start container: start container: started hook: container exec create: Error response from daemon: container b1e332e5aaf38ea01512481ebb257946551b61fc9ad4d56b0d15f1c2cc27eafa is not running
        all exposed ports, [27017/tcp], were not mapped in 5s: port 27017/tcp is not mapped yet
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by abhipranay**
## What does this PR do?

This PR fixes the bug for mongodb module where container doesn't start when `WithReplicaSet` option is used in combination with `WithUsername` and `WithPassword`.

## Why is it important?

Fixes the issue mentioned in #2755.
Idea here is to use wrapping entrypoint so that security keyfile can be created with proper permissions and under correct ownership.
Wrapper entrypoint is used only when necessary and not always.

The functional option pattern make it difficult to figure out what were all the configured options so we are using `req.Env` to share data across funtions.

## Related issues

- Closes #2755

### CODE REVIEW

File: modules/mongodb/mount/entrypoint.sh [hunk 1]
```diff
@@ -0,0 +1,9 @@
+#!/bin/bash
+
+set -Eeuo pipefail
+
+openssl rand -base64 756 > "${MONGO_KEYFILE}"
+chown "${MONGO_USER_GROUP}" "${MONGO_KEYFILE}"
```
Comment (abhipranay) [inline modules/mongodb/mount/entrypoint.sh:6]: I will enhance this through auto detection so that it works for all images.

File: modules/mongodb/mongodb.go [hunk 2]
```diff
@@ -129,14 +131,77 @@ func (c *MongoDBContainer) ConnectionString(ctx context.Context) (string, error)
...
+		return nil
+	}
+}
+
+func initiateReplicaSet(req *testcontainers.GenericContainerRequest, cli mongoCli, replSetName string) {
+	req.WaitingFor = wait.ForAll(
+		req.WaitingFor,
+		wait.ForExec(cli.eval("rs.status().ok")),
+	).WithDeadline(60 * time.Second)
+	req.LifecycleHooks = append(
```
Comment (mdelapenya) [inline modules/mongodb/mongodb.go:173]: Personal Nit: adding an empty line helps in readability in this block. Probably applicable to other places 🙏

File: modules/mongodb/mongodb_test.go [hunk 3]
```diff
@@ -56,6 +56,59 @@ func TestMongoDB(t *testing.T) {
 				mongodb.WithReplicaSet("rs"),
 			},
 		},
+		{
+			name: "With Auth, Replica set and mongo:7",
```
Comment (mdelapenya) [inline modules/mongodb/mongodb_test.go:60]: suggestion: even though the previos test names are using sentences, where are moving away from them, instead using dashes and using and imperative style. Something like this:
```suggestion
			name: "with-auth/replica/mongo:7",
```

So please use this as reference in the new tests you added. And if you update the existing tests in this file, a separate commit for separation of concerns, that would be a perfect boy-scout trip!

File: modules/mongodb/mount/entrypoint.sh [hunk 4]
```diff
@@ -0,0 +1,32 @@
+#!/bin/bash
```
Comment (mdelapenya) [inline modules/mongodb/mount/entrypoint.sh:1]: I'd rename this to `entrypoint-tc.sh` in order to make it explicit this is added and executed by Testcontainers. Also adding a comment with something like "# Injected by Tescontainers" could be interesting.

**Review by mdelapenya — COMMENTED** [review]
It LGTM, although I left a few comments. I tested it locally and it indeed resolves the issues described in the original ticket, so thank you for working on this

File: modules/mongodb/mongodb.go (hunk 2 above)
Comment (abhipranay) [reply modules/mongodb/mongodb.go:173]: I will do the final touchup.

**Review by mdelapenya — APPROVED** [review]
LGTM, thanks for contributing the fix! Also for creating such a great commit history that allowed me to loop through it with ease.

@stevenh do you want to take a final look on it?

**Comment by mdelapenya** [comment]
@abhipranay I added a commit on top with the fix for the lint: running `make lint` from the mongodb dir did the trick.

**Review by mdelapenya — APPROVED** [review]
LGTM, thanks!
