### PR TITLE
fix: use first exposed port by default in HTTP wait strategy

### LINKED ISSUE #1083: [Enhancement]: wait.ForHTTP should default to examining mapped ports instead of port 80
### Proposal

Currently, `wait.ForHTTP` defaults to port 80

https://github.com/testcontainers/testcontainers-go/blob/main/wait/http.go#L44

This causes a lot of confusion if leaving out `WithPort` to specify a correct port, with a "can't find port" error that isn't very explanatory, and I think happens in many cases since a port of 80 is often not exposed in normal containers.

It would be great if it instead inspected the mapped ports to do the check when an explicit one is not satisfied. I believe this is how Java behaves.

Alternatively, I would have `ForHttp` accept two parameters, the path and port, making port a required parameter rather than hoping port 80 may work, I think it's quite rare.

### PR DESCRIPTION
**Pull request by anuraaga**
## What does this PR do?

Instead of using port 80 as a default, HTTP wait strategy contains no default. If the user does not set an explicit port, the first exposed port is automatically used for liveness checking.

## Why is it important?

It can be surprising when an HTTP wait strategy fails with a port-related error when not explicitly setting a port to check as it tries on port 80. It becomes easier to use if it just automatically uses the first exposed port, which will be correct in a large number of cases, while explicit port can still be used otherwise.

This aligns the behavior with testcontainers-java which has always inspected the ports as a default

https://github.com/testcontainers/testcontainers-java/blob/main/core/src/main/java/org/testcontainers/containers/wait/strategy/HttpWaitStrategy.java#L220

## Related issues

- Closes #1083

Setting a HTTP wait strategy without specifying a port while running a container that does not use port 80.

### CODE REVIEW

File: wait/http.go [hunk 1]
```diff
@@ -142,24 +142,50 @@ func (ws *HTTPStrategy) WaitUntilReady(ctx context.Context, target StrategyTarge
...
+				return fmt.Errorf("%s:%w", ctx.Err(), err)
+			case <-time.After(ws.PollInterval):
+				if err := checkTarget(ctx, target); err != nil {
+					return err
+				}
+
+				ports, err = target.Ports(ctx)
+			}
+		}
+		for k, bindings := range ports {
```
Comment (mdelapenya) [inline wait/http.go:160]: Let's create a visual separation of concerns here
```suggestion
		}

		for k, bindings := range ports {
```

File: wait/http.go [hunk 2]
```diff
@@ -142,24 +142,50 @@ func (ws *HTTPStrategy) WaitUntilReady(ctx context.Context, target StrategyTarge
...
+			if len(bindings) == 0 || k.Proto() != "tcp" {
+				continue
+			}
+			mappedPort, _ = nat.NewPort(k.Proto(), bindings[0].HostPort)
+			break
+		}
+		if mappedPort == "" {
```
Comment (mdelapenya) [inline wait/http.go:167]: Same here
```suggestion
		}

		if mappedPort == "" {
```

**Review by mdelapenya — COMMENTED** [review]
Just a few comments regarding code style, but other than that, great job with the tests!

And sorry for taking that long with the review 🙏 I will focus on this PR this week, so it will get hopefully merged into the project. Thanks!

**Comment by anuraaga** [comment]
Thanks @mdelapenya updated with the suggestions

**Comment by anuraaga** [comment]
Sure - I updated the docs snippets to elide the port, let me know if that's what you were looking for

File: wait/http_test.go [hunk 3]
```diff
@@ -55,7 +55,7 @@ func ExampleHTTPStrategy_WithBasicAuth() {
 	req := testcontainers.ContainerRequest{
 		Image:        "gogs/gogs:0.11.91",
 		ExposedPorts: []string{"3000/tcp"},
-		WaitingFor:   wait.ForHTTP("/").WithPort("3000/tcp").WithBasicAuth("username", "password"),
+		WaitingFor:   wait.ForHTTP("/").WithBasicAuth("username", "password"),
```
Comment (mdelapenya) [inline wait/http_test.go:58]: I would keep the `WithPort` part for the docs sections, as user could still want to see it in the code snippets regarding HTTP wait.

I'd add a new section in the docs, e.g. `Match an HTTP method with Port` keeping the old snippet as is, and in the current `Match an HTTP method`, I'd link it to the test code actually not using the `WithPort`.

If you are not sure on this, I can send a follow-up PR refining the docs, whatever you prefer is fine.

Comment (anuraaga) [reply wait/http_test.go:85]: Ah OK I added back an example with `WithPort` - I added an unrelated port to the `ExposedPorts` to illustrate where it would be useful

File: docs/features/wait/http.md [hunk 4]
```diff
@@ -21,6 +21,12 @@ Variations on the HTTP wait strategy are supported, including:
 [Waiting for an HTTP endpoint](../../../wait/http_test.go) inside_block:waitForHTTP
 <!--/codeinclude-->
 
+## Match an HTTP method with Port
+
+<!--codeinclude-->
+[Waiting for an HTTP endpoint](../../../wait/http_test.go) inside_block:waitForHTTPWithPorg
```
Comment (mdelapenya) [inline docs/features/wait/http.md:27]:
```suggestion
[Waiting for an HTTP endpoint](../../../wait/http_test.go) inside_block:waitForHTTPWithPort
```

Comment (anuraaga) [reply docs/features/wait/http.md]: Doh, thanks

File: docs/features/wait/http.md [hunk 5]
```diff
@@ -21,6 +21,12 @@ Variations on the HTTP wait strategy are supported, including:
 [Waiting for an HTTP endpoint](../../../wait/http_test.go) inside_block:waitForHTTP
 <!--/codeinclude-->
 
+## Match an HTTP method with Port
+
+<!--codeinclude-->
+[Waiting for an HTTP endpoint](../../../wait/http_test.go) inside_block:waitForHTTPWithPort
```
Comment (mdelapenya) [inline docs/features/wait/http.md:27]: For some reason, this locator it causing issues when rendering the mkdocs site: https://deploy-preview-1086--testcontainers-go.netlify.app/features/wait/http/

Could you check why? I'd also include a paragraph explaining what you described in the PR description:

> Instead of using port 80 as a default, HTTP wait strategy contains no default. If the user does not set an explicit port, the first exposed port is automatically used for liveness checking.

I think a good place would be right before the `variations` section.

You can simply test it locally using the instructions here: https://deploy-preview-1086--testcontainers-go.netlify.app/contributing_docs/#previewing-rendered-content

Comment (anuraaga) [reply docs/features/wait/http.md:27]: Thanks for these pointers - sorry about it will take a look next week

Comment (mdelapenya) [reply docs/features/wait/http.md:27]: Hey @anuraaga please let me know if I can be of any help with the docs here 🙏  I'd like to include this fix into the project :)

Comment (mdelapenya) [reply docs/features/wait/http.md:27]: @anuraaga I'm going ahead and fixing this by myself. If you don't mind, I'm going to push my commits right after yours.

File: docs/features/wait/http.md [hunk 6]
```diff
@@ -2,7 +2,7 @@
 
 The HTTP wait strategy will check the result of an HTTP(S) request against the container and allows to set the following conditions:
 
-- the port to be used.
+- the port to be used. If no port is passed, it will use first exposed port in the image.
```
Comment (mdelapenya) [inline docs/features/wait/http.md:5]:
```suggestion
- the port to be used. If no port is passed, it will use the first exposed port in the image.
```

**Review by mdelapenya — APPROVED** [review]
LGTM! Thanks @anuraaga for your efforts in contributing to testcontainers-go. Really appreciated! 🙇 

Waiting for the CI to merge it

**Comment by anuraaga** [comment]
@mdelapenya Thanks so much and sorry for causing extra work 🙏 Meant to find the time - for the last fix but just wasn't able to, thank you

**Comment by mdelapenya** [comment]
No worries at all, I sincerely understand that sometimes finding time for OSS is more than difficult. I as an OSS maintainer try to promote the community work and, when possible, be the degreaser on blockers of any type :)
