### PR TITLE
fix: do not override ImageBuildOptions.Labels when building from a Dockerfile

### LINKED ISSUE #2632: [Bug]: ImageBuildOptions.Labels are overwritten
### Testcontainers version

v0.32.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x86

### Go version

1.22

### Docker version

```shell
Client: Docker Engine - Community
 Version:           27.0.3
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7d4bcd8
 Built:             Sat Jun 29 00:02:26 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.0.3
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       662f78c
  Built:            Sat Jun 29 00:02:26 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.18
  GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc:
  Version:          1.7.18
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client: Docker Engine - Community
 Version:    27.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.28.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 36
  Running: 1
  Paused: 0
  Stopped: 35
 Images: 769
 Server Version: 27.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-42-generic
 Operating System: Ubuntu 23.10
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.01GiB
 Name: thorx1
 ID: 94633125-a6fc-41db-ba45-8e359b3bb5ef
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  dkr.vrit.dev:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

In line https://github.com/testcontainers/testcontainers-go/blob/d94455b5799ffe6909eb403dbdba38e2e69fd77a/container.go#L394-L396 the labels that are set in https://github.com/testcontainers/testcontainers-go/blob/d94455b5799ffe6909eb403dbdba38e2e69fd77a/container.go#L352-L354 are overwriten. The keys should be merged instead of overwritten.

### Relevant log output

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rzajac**
Closes #2632.

### CODE REVIEW

File: internal/core/labels_test.go [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+		// --- Given ---
+		dst := map[string]string{"A": "1", "B": "2"}
+		src := map[string]string{"B": "X", LabelLang: "go"}
+
+		// --- When ---
+		err := MergeCustomLabels(dst, src)
+
+		// --- Then ---
+		want := `cannot use prefix "org.testcontainers" for custom labels`
+		require.Error(t, err, want)
```
Comment (stevenh) [inline internal/core/labels_test.go:34]: suggestion: use `EqualError` to assert the right error:
```suggestion
		require.EqualError(t, err, `cannot use prefix "org.testcontainers" for custom labels`)
```

File: internal/core/labels_test.go [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+		// --- Given ---
+		dst := map[string]string{"A": "1", "B": "2"}
+		src := map[string]string{"B": "X", "C": "3"}
+
+		// --- When ---
+		err := MergeCustomLabels(dst, src)
+
+		// --- Then ---
+		require.NoError(t, err)
+		assert.Equal(t, map[string]string{"A": "1", "B": "X", "C": "3"}, dst)
```
Comment (stevenh) [inline internal/core/labels_test.go:21]: suggestion: Lets always use require so we don't suffer from knock on errors and keep it all consistent, more below
```suggestion
		require.Equal(t, map[string]string{"A": "1", "B": "X", "C": "3"}, dst)
```

File: internal/core/labels_test.go [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+
+import (
+	"testing"
+
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
+)
+
+func TestMergeCustomLabels(t *testing.T) {
+	t.Run("merge success", func(t *testing.T) {
```
Comment (stevenh) [inline internal/core/labels_test.go:11]: suggestion: keep test names simple and avoid spaces to they can be search for, spaces are placed by underscore.
```suggestion
	t.Run("success", func(t *testing.T) {
```

File: internal/core/labels_test.go [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+		// --- Given ---
+		dst := map[string]string{"A": "1", "B": "2"}
+		src := map[string]string{"B": "X", "C": "3"}
+
+		// --- When ---
+		err := MergeCustomLabels(dst, src)
+
+		// --- Then ---
```
Comment (stevenh) [inline internal/core/labels_test.go:19]: suggestion: lets remove the comments, as they don't tell the reader anything more than the code itself.

My rule for comments, is they should tell the user something they might otherwise not understand.

move below.
```suggestion
		dst := map[string]string{"A": "1", "B": "2"}
		src := map[string]string{"B": "X", "C": "3"}

		err := MergeCustomLabels(dst, src)
```

**Review by stevenh — CHANGES_REQUESTED** [review]

File: internal/core/labels.go [hunk 5]
```diff
@@ -21,3 +24,20 @@ func DefaultLabels(sessionID string) map[string]string {
 		LabelVersion:   internal.Version,
 	}
 }
+
+// MergeCustomLabels sets labels from src to dst. Returns error if src label
+// name has [LabelBase] prefix.
+//
+// NOTICE: Default labels must not be nil.
```
Comment (mdelapenya) [inline internal/core/labels.go:31]: Is it a typo?
```suggestion
// NOTICE: dst labels must not be nil.
```

File: internal/core/labels_test.go [hunk 6]
```diff
@@ -0,0 +1,32 @@
...
+	t.Run("success", func(t *testing.T) {
+		dst := map[string]string{"A": "1", "B": "2"}
+		src := map[string]string{"B": "X", "C": "3"}
+
+		err := MergeCustomLabels(dst, src)
+		require.NoError(t, err)
+		require.Equal(t, map[string]string{"A": "1", "B": "X", "C": "3"}, dst)
+	})
+
+	t.Run("src cannot have keys starting with LabelBase", func(t *testing.T) {
```
Comment (mdelapenya) [inline internal/core/labels_test.go:20]: I think we should apply here same suggestions regarding comments and subtest name

File: container_test.go [hunk 7]
```diff
@@ -303,6 +304,71 @@ func Test_BuildImageWithContexts(t *testing.T) {
...
+	ctr, err := testcontainers.GenericContainer(ctx, req)
+
+	// --- Then ---
+	require.NoError(t, err)
+	t.Cleanup(func() { assert.NoError(t, ctr.Terminate(ctx)) })
+
+	ctrJSON, err := ctr.Inspect(ctx)
+	require.NoError(t, err)
+	assert.Equal(t, myLabelValue, ctrJSON.Config.Labels[myLabelName])
+	assert.Equal(t, myBuildOptionValue, ctrJSON.Config.Labels[myBuildOptionLabel])
```
Comment (mdelapenya) [inline container_test.go:369]: Let's use require here too
```suggestion
	require.Equal(t, myLabelValue, ctrJSON.Config.Labels[myLabelName])
	require.Equal(t, myBuildOptionValue, ctrJSON.Config.Labels[myBuildOptionLabel])
```

File: container_test.go [hunk 8]
```diff
@@ -303,6 +304,71 @@ func Test_BuildImageWithContexts(t *testing.T) {
...
+				},
+			},
+			Labels: map[string]string{myLabelName: myLabelValue},
+		},
+	}
+
+	// --- When ---
+	ctr, err := testcontainers.GenericContainer(ctx, req)
+
+	// --- Then ---
```
Comment (mdelapenya) [inline container_test.go:362]: Let's also remove the comments: if the code is explicit enough, then comments should not be added. So comments must be added to add clarity on the block they belong.

**Review by mdelapenya — COMMENTED** [review]
Just added a few minor comments regarding previous suggestions by @stevenh (thanks!)

I think, once resolved, we are good to go.

Thanks!

File: internal/core/labels.go [hunk 9]
```diff
@@ -21,3 +24,19 @@ func DefaultLabels(sessionID string) map[string]string {
 		LabelVersion:   internal.Version,
 	}
 }
+
+// MergeCustomLabels sets labels from src to dst. Returns error if src label
+// name has [LabelBase] prefix.
+//
+// NOTICE: dst labels must not be nil.
```
Comment (stevenh) [inline internal/core/labels.go:31]: suggestion: if it must not be nil, test it and error?

File: internal/core/labels_test.go [hunk 10]
```diff
@@ -0,0 +1,29 @@
...
+		dst := map[string]string{"A": "1", "B": "2"}
+		src := map[string]string{"B": "X", LabelLang: "go"}
+
+		err := MergeCustomLabels(dst, src)
+
+		require.EqualError(t, err, `cannot use prefix "org.testcontainers" for custom labels`)
+		assert.Equal(t, map[string]string{"A": "1", "B": "X"}, dst)
```
Comment (stevenh) [inline internal/core/labels_test.go:27]: suggestion: lets use require for all, prevents issues with knock on failures, so a good habit to get into.
```suggestion
		require.Equal(t, map[string]string{"A": "1", "B": "X"}, dst)
```

**Review by stevenh — CHANGES_REQUESTED** [review]
Just two little fixes, then should be good to go.

File: internal/core/labels_test.go [hunk 11]
```diff
@@ -0,0 +1,44 @@
...
+	t.Run("success", func(t *testing.T) {
+		dst := map[string]string{"A": "1", "B": "2"}
+		src := map[string]string{"B": "X", "C": "3"}
+
+		err := MergeCustomLabels(dst, src)
+		require.NoError(t, err)
+		require.Equal(t, map[string]string{"A": "1", "B": "X", "C": "3"}, dst)
+	})
+
+	t.Run("src cannot have keys starting with LabelBase", func(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (mdelapenya) [reply internal/core/labels_test.go:19]: I'm following this pattern in new tests @stevenh, thanks for bringing it to the project!

**Review by mdelapenya — COMMENTED** [review]
@rzajac I think this PR looks really good, thanks for addressing all our comments and sorry of they took that long 🙏 

Once the last final suggestions are addressed, I think we are good to go. In the meantime, it LGTM (will approve once they CI passes too).

**Comment by rzajac** [comment]
@mdelapenya Glad to be of help!

**Review by stevenh — APPROVED** [review]
Nice, thanks for doing this.

File: container_test.go [hunk 12]
```diff
@@ -303,6 +304,65 @@ func Test_BuildImageWithContexts(t *testing.T) {
...
+				},
+			},
+			Labels: map[string]string{myLabelName: myLabelValue},
+		},
+	}
+
+	ctr, err := testcontainers.GenericContainer(ctx, req)
+
+	require.NoError(t, err)
+	t.Cleanup(func() { assert.NoError(t, ctr.Terminate(ctx)) })
```
Comment (mdelapenya) [inline container_test.go:358]: Let's use the new APIs for cleaning up containers in tests
```suggestion
	ctr, err := testcontainers.GenericContainer(ctx, req)
	testcontainers.CleanupContainer(t, ctr)
	require.NoError(t, err)
```

**Review by mdelapenya — COMMENTED** [review]
Just one last minute change, regarding how the test is cleaning up the created container.

Right after that, we are good to go, thanks!

**Review by mdelapenya — APPROVED** [review]
LGTM, thanks for your patience during the review 🙇
