### PR TITLE
fix: prefer cross-platform default DOCKER_HOST

### LINKED ISSUE #1249: [Bug]: Failing with "protocol not available, failed to create Docker provider" on Windows
### Testcontainers version

0.20.1

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host arch

x86

### Go version

1.20

### Docker version

```shell
Client:
 Cloud integration: v1.0.31
 Version:           23.0.5
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        bc4487a
 Built:             Wed Apr 26 16:20:14 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.19.0 (106363)
 Engine:
  Version:          23.0.5
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       94d3ad6
  Built:            Wed Apr 26 16:17:45 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.10.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 167
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.48GiB
 Name: docker-desktop
 ID: 833c289d-cefa-4019-a820-b1b496cc06f6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

I upgraded from `v0.19.0` using `go get -u` and got the latest `v0.20.1`.

To my surprise running the same tests that had just passed now fails consistently with the message: 
> protocol not available, failed to create Docker provider

Looking deeper into the changelog of this release I see the error comes from `sockets.ConfigureTransport(transport, c.proto, c.addr)` at `github.com/docker/docker@v24.0.2+incompatible/client/options.go:71`.

This option function (`client.WithHost`) is not called by the previous version because of the introduction of [`ReadConfig()`](https://github.com/testcontainers/testcontainers-go/blob/675cb128859ae123de07c911ab9e75e9a241238a/config.go#L30).

Previously, this option is only appended by [`NewDockerClient()`](https://github.com/testcontainers/testcontainers-go/blob/2f49f6ee39ad7a17786cf1c89fdecb0f28092f79/docker.go#L763) only if the user-environment contains a `.testcontainers.properties` file that explicitly sets the docker host.

Nowadays, this option is always appended by [`NewDockerClient()`](https://github.com/testcontainers/testcontainers-go/blob/675cb128859ae123de07c911ab9e75e9a241238a/docker.go#L781) because [`ReadConfig()`](https://github.com/testcontainers/testcontainers-go/blob/675cb128859ae123de07c911ab9e75e9a241238a/config.go#L50) always returns constant host, even when not explicitly set by the user-environment.

### Relevant log output

I've summarized the difference between the two tags (ignoring comments and whitespaces):

```diff
1,3c1,2
< func NewDockerClient() (cli *client.Client, host string, tcConfig TestContainersConfig, err error) {
< 	tcConfig = configureTC()
< 	host = tcConfig.Host
---
> func NewDockerClient() (cli *client.Client, err error) {
> 	tcConfig := ReadConfig()
6,7c5,6
< 	if host != "" {
< 		opts = append(opts, client.WithHost(host))
---
> 	if tcConfig.Host != "" {
> 		opts = append(opts, client.WithHost(tcConfig.Host))
17,20d15
< 	} else if dockerHostEnv := os.Getenv("DOCKER_HOST"); dockerHostEnv != "" {
< 		host = dockerHostEnv
< 	} else {
< 		host = "unix:///var/run/docker.sock"

```

### Additional information

Eventually, on Windows without any custom configuration, `v0.19.0` used to access the host `npipe:////./pipe/docker_engine`.
Without the [`client.WithHost()`](https://github.com/moby/moby/blob/659604f9ee60f147020bdd444b26e4b5c636dc28/client/options.go#L60) option, the [`DefaultDockerHost`](https://github.com/moby/moby/blob/659604f9ee60f147020bdd444b26e4b5c636dc28/client/client_windows.go#L5) is used correctly for Windows and never overridden.

### PR DESCRIPTION
**Pull request by danielorbach**
Instead of blindly assuming a Linux operating system we can rely on the docker client package to tell us the appropriate default docker host.

## What does this PR do?

I've changed the default `DOCKER_HOST` socket from its Linux value by relying on Docker's client library to supply their cross-platform values.

I chose to parse their value as a URL (I say `parseURL` doing the same) to separate between the schema and the path.

I was defensive because I am unfamiliar with the codebase - that's the reason for the suffix/prefix validations. Also, upon errors (url parsing, or unknown schema) I fallback to the predefined default rendering the changes of this PR a no-op.

## Why is it important?

Windows users really want to use test-containers too! 🪟🐳 

Before release `v0.20.1` the host was not explicitly set to a default, hence it fell-back to the docker library's default anyways.

## Related issues

- Closes #1249 

## How to test this PR

I haven't been able to run all the tests because I currently use a Windows machine. However, I ran some container-based tests (that broke with release `v0.20.1`) on my machine and they have passed 🤗

### CODE REVIEW

File: internal/testcontainersdocker/docker_socket.go [hunk 1]
```diff
@@ -11,3 +18,24 @@ var DockerSocketPathWithSchema = DockerSocketSchema + DockerSocketPath
 
 // TCPSchema is the tcp schema.
 var TCPSchema = "tcp://"
+
+func init() {
```
Comment (mdelapenya) [inline internal/testcontainersdocker/docker_socket.go:22]: I had a local branch doing something similar, but creating a `docker_socket_windows.go` file, directly assigning the values we need:

```go
// DockerSocketSchema is the npipe schema.
var DockerSocketSchema = "npipe://"

// DockerSocketPath is the path to the docker socket under Windows systems.
var DockerSocketPath = "//./pipe/docker_engine"
```

I'm not sure if we should use this simpler approach, or instead delegate to the docker client as in this PR. What are your thoughts on this?

Comment (danielorbach) [reply internal/testcontainersdocker/docker_socket.go:22]: That would've solved it for sure! 🛬

I'm in favour of delegating to the Docker library because it honours their responsibility, in my mind.

However, you've already chosen to use a hard-coded value, therefore I'd support your approach blindly 😎 you definitely know best.

Let me know how you'd like to proceed. I'm available to make the desired changes.

Comment (mdelapenya) [reply internal/testcontainersdocker/docker_socket.go:22]: >I'm in favour of delegating to the Docker library because it honours their responsibility, in my mind.

I like this too. I think we can stick to it. Thanks for your support!

**Review by mdelapenya — DISMISSED** [review]
Given the Docker client already does what I suggested in https://github.com/testcontainers/testcontainers-go/pull/1294/files#r1231789163, I think it's safer to honour the Docker client, as proposed in this PR.

Shaun approves 😎 

image

File: internal/testcontainersdocker/docker_socket.go [hunk 2]
```diff
@@ -11,3 +18,24 @@ var DockerSocketPathWithSchema = DockerSocketSchema + DockerSocketPath
...
+		// unsupported default host specified by the docker client package,
+		// so revert to the default unix docker socket path
+		return
+	}
+
+	switch u.Scheme {
+	case "unix", "npipe":
+		DockerSocketSchema = u.Scheme + "://"
+		DockerSocketPath = u.Path
+		if !strings.HasPrefix(DockerSocketPath, "/") {
```
Comment (mdelapenya) [inline internal/testcontainersdocker/docker_socket.go:36]: One question: when does the `DockerSocketPath`, read from `u.Path` will not start with `/`?

Do you think this check is possible, given the docker client returns two possible values here?:
- npipe:////./pipe/docker_engine
- unix:///var/run/docker.sock

Comment (danielorbach) [reply internal/testcontainersdocker/docker_socket.go:36]: I proceeded with caution seeing as the code in this module depends on the presence of said `/`.
For the known environments I do not see how it should miss the slash, however I think this extra if-condition is worth to save future pain from innocent users.

Comment (mdelapenya) [reply internal/testcontainersdocker/docker_socket.go:36]: OK, let's keep it, although I'd appreciate adding there a comment explaining why 🙏 

Once added, this is ready to be shipped! 🛥️

Comment (danielorbach) [reply internal/testcontainersdocker/docker_socket.go:36]: Done 🗯️

Comment (danielorbach) [reply internal/testcontainersdocker/docker_socket.go:36]: You are correct, I've pulled latest changes from `main` however I forgot to commit the comment @mdelapenya

**Comment by mdelapenya** [comment]
@mehdihadeli we are going to release a new version soon, hopefully at the end of this week

**Comment by mehdihadeli** [comment]
Thanks

**Comment by danielorbach** [comment]
> @danielorbach Hi, thanks for the fix, Did you publish a new package release for this fix?

@mdelapenya I haven't a clue how to do this 😅
