### PR TITLE
(#128) Throw an error when bash is not installed in the target container

### LINKED ISSUE #128: WaitForHostPort for depends on `bash` being installed in the target service
## Bug description
I noticed that the wait for host/port strategy depends on having `bash` installed in the target service:

https://github.com/testcontainers/testcontainers-go/blob/cb2a3aa5304fa2e6af5c693063176fdd2319e3ab/wait/host_port.go#L91

which could not be true in many scenarios (i.e. a very basic Alpine-based image)

## Steps To Reproduce
Create a ContainerRequest from an Image without bash installed on it. Add a wait.ForListeningPort strategy. It will create an infinite loop as the exit code is not controlled, delegating the exit of the test method to the Docker client, which is not able to close the initial command.

```shell
panic: test timed out after 30s

goroutine 616 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:1377 +0xdf
created by time.goFunc
	/usr/local/Cellar/go/1.13.4/libexec/src/time/sleep.go:168 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000ef300, 0x164630d, 0x30, 0x16538e0, 0x1087f01)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:961 +0x377
testing.runTests.func1(0xc0000ef200)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:1202 +0x78
testing.tRunner(0xc0000ef200, 0xc0001f3dc0)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:909 +0xc9
testing.runTests(0xc000236fa0, 0x1ab15a0, 0x19, 0x19, 0x0)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:1200 +0x2a7
testing.(*M).Run(0xc0000edd00, 0x0)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:1117 +0x176
main.main()
	_testmain.go:92 +0x135

goroutine 36 [IO wait]:
internal/poll.runtime_pollWait(0x1e51600, 0x72, 0xffffffffffffffff)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000426518, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/Cellar/go/1.13.4/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.13.4/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000426500, 0xc000440000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.4/libexec/src/internal/poll/fd_unix.go:169 +0x22b
net.(*netFD).Read(0xc000426500, 0xc000440000, 0x1000, 0x1000, 0x16ea940, 0xc00025fb80, 0x0)
	/usr/local/Cellar/go/1.13.4/libexec/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000612690, 0xc000440000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.4/libexec/src/net/net.go:184 +0x68
net/http.(*persistConn).Read(0xc0003f7c20, 0xc000440000, 0x1000, 0x1000, 0x0, 0xc0001752e8, 0x100e216)
	/usr/local/Cellar/go/1.13.4/libexec/src/net/http/transport.go:1752 +0x75
bufio.(*Reader).Read(0xc000490c60, 0xc0005be000, 0x200, 0x2000, 0x8, 0x1585b20, 0x6db7ac1ba336768e)
	/usr/local/Cellar/go/1.13.4/libexec/src/bufio/bufio.go:226 +0x26a
net/http.(*body).readLocked(0xc000388700, 0xc0005be000, 0x200, 0x2000, 0xc, 0xc000413ec8, 0xc0001753a8)
	/usr/local/Cellar/go/1.13.4/libexec/src/net/http/transfer.go:847 +0x5f
net/http.(*body).Read(0xc000388700, 0xc0005be000, 0x200, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.4/libexec/src/net/http/transfer.go:839 +0x102
net/http.(*bodyEOFSignal).Read(0xc000388740, 0xc0005be000, 0x200, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.4/libexec/src/net/http/transport.go:2576 +0xe5
io.(*LimitedReader).Read(0xc00044b520, 0xc0005be000, 0x2000, 0x2000, 0xc000434090, 0x100b07b, 0xc000012000)
	/usr/local/Cellar/go/1.13.4/libexec/src/io/io.go:448 +0x63
io/ioutil.devNull.ReadFrom(0x0, 0x16ea760, 0xc00044b520, 0x1593760, 0x1, 0x1e51770)
	/usr/local/Cellar/go/1.13.4/libexec/src/io/ioutil/ioutil.go:147 +0x92
io.copyBuffer(0x16eb5a0, 0x1ad3b00, 0x16ea760, 0xc00044b520, 0x0, 0x0, 0x0, 0x1596f80, 0x16f0900, 0x16ea980)
	/usr/local/Cellar/go/1.13.4/libexec/src/io/io.go:388 +0x2ed
io.Copy(...)
	/usr/local/Cellar/go/1.13.4/libexec/src/io/io.go:364
io.CopyN(0x16eb5a0, 0x1ad3b00, 0x16ea980, 0xc000388740, 0x200, 0xc0002df0b0, 0xc8, 0xc000406d80)
	/usr/local/Cellar/go/1.13.4/libexec/src/io/io.go:340 +0x9a
github.com/docker/docker/client.ensureReaderClosed(0x16f0980, 0xc000388740, 0xc0002df0b0, 0xc8, 0xc000406d80)
	/Users/mdelapenya/sourcecode/pkg/mod/github.com/docker/engine@v0.0.0-20190717161051-705d9623b7c1/client/request.go:270 +0x90
github.com/docker/docker/client.(*Client).ContainerExecStart(0xc0000ede00, 0x16f6500, 0xc0003d8000, 0xc0001af840, 0x40, 0x0, 0x0, 0x0)
```

## Expected behavior
The error level 126 (`command not executable`) should be managed.

## docker info

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 266
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.787GiB
 Name: docker-desktop
 ID: 666N:ZRUC:5URC:56ID:255A:GL7H:ZM2Y:M25P:EW3W:YE52:URT7:5EGH
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 39
  Goroutines: 54
  System Time: 2020-01-07T10:55:22.0569905Z
  EventsListeners: 2
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

## Additional context
Many tests are using a pre-baked imaged `menedev/delayed-nginx:1.15.2` which contains `bash`. I'd go with official images for this kind of tests.

I wonder if this approach, using `bash` is valid for Windows containers... 🤔

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
It throws an error when the evaluation of the '/bin/bash' command used to
check the host/port in the target container fails because 'bash' is not
present in the system (as it happens in most Alpine-based images).

## Why is it important?
It will make the checks more reliable, as the implementation will raise an
error that could be handled by client code.

Before this change, the client code waited and a timeout happened. Now a more
accurate error is raised so it's easier to handle.

## Related issues
Closes #128

### CODE REVIEW

File: wait/host_port.go [hunk 1]
```diff
@@ -88,13 +88,15 @@ func (hp *HostPortStrategy) WaitUntilReady(ctx context.Context, target StrategyT
...
-		exitCode, err := target.Exec(ctx, []string{"/bin/bash", "-c", command})
+		exitCode, err := target.Exec(ctx, []string{"/bin/sh", "-c", command})
 		if err != nil {
 			return errors.Wrapf(err, "host port waiting failed")
 		}
 
 		if exitCode == 0 {
 			break
+		} else if exitCode == 126 {
+			return errors.New("/bin/sh command not executable")
```
Comment (ClaytonNorthey92) [inline wait/host_port.go]: what would the `err` variable have in this case? I am not sure without testing...but would it be better to
```go
if exitCode == 0 {
    break
} else {
    return fmt.Errorf("received exit code %d when running /bin/sh, error: %s", exitCode, err)
}
```
or something similar?  that way we handle for any exit code that is not a 0

Comment (mdelapenya) [reply wait/host_port.go]: `err` would be nil, otherwise L92  will capture it

Comment (ClaytonNorthey92) [reply wait/host_port.go]: ah I missed that, thanks!

**Comment by mdelapenya** [comment]
reopening for travis to rebuild

File: wait/host_port.go [hunk 2]
```diff
@@ -88,13 +88,15 @@ func (hp *HostPortStrategy) WaitUntilReady(ctx context.Context, target StrategyT
 	//internal check
 	command := buildInternalCheckCommand(hp.Port.Int())
 	for {
-		exitCode, err := target.Exec(ctx, []string{"/bin/bash", "-c", command})
+		exitCode, err := target.Exec(ctx, []string{"/bin/sh", "-c", command})
```
Comment (nikolayk812) [inline wait/host_port.go]: it was a bug, yes, sorry for that

File: wait/host_port.go [hunk 3]
```diff
@@ -105,7 +107,7 @@ func buildInternalCheckCommand(internalPort int) string {
 	command := `(
 					cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :%x ||
 					nc -vz -w 1 localhost %d ||
-					/bin/bash -c '</dev/tcp/localhost/%d'
+					/bin/sh -c '</dev/tcp/localhost/%d'
```
Comment (nikolayk812) [inline wait/host_port.go]: this is unnecessary, I believe. External command fix should be enough.

**Comment by nikolayk812** [comment]
@mdelapenya are you planning to fix this branch?

File: wait/host_port.go (hunk 3 above)
Comment (mdelapenya) [reply wait/host_port.go]: Hey, sorry for the late response. I'll revert this change and resend. TBH, not sure why the travis tests fail tough.

Comment (mdelapenya) [reply wait/host_port.go]: Mmmm, thinking about it, the internal command should be `sh`, because it's very likely that `bash` is not present in the container (i.e. Alpine-based images)

**Comment by mdelapenya** [comment]
> @mdelapenya are you planning to fix this branch?

Yes, the thing is I'm not sure why the tests are failing on Travis 🤷‍♀ I'm debugging locally trying to find the issue

**Comment by mdelapenya** [comment]
After debugging this before the `sh` replacement (37e3ccb103601a6f73e8739ea365978a89f5e77f) and after it (8e056dec4677af9d702c65de945e6bf05bc993d5) I can see that the execution of the `buildInternalCheckCommand` is causing the problem.

The below output comes from debugging `TestContainerCreationAndWaitForListeningPortLongEnough` from VSCode **before** replacing BASH, adding a breakpoint at `host_port.go`:

```golang
exitCode, err := target.Exec(ctx, []string{"/bin/bash", "-c", command})
```
The generated command is:
```shell
true && (
					cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :50 ||
					nc -vz -w 1 localhost 80 ||
					/bin/bash -c '</dev/tcp/localhost/80'
				)
```

Entering into the created container (`docker exec -ti`), I can execute each of those subcommands:
```
root@16589f2fd2e4:/# cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :50                                               
root@16589f2fd2e4:/# cat /proc/net/tcp{,6} | awk '{print $2}'              
local_address
00000000:0050
0100007F:8200
0100007F:81F4
local_address
root@16589f2fd2e4:/# cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :0050
00000000:0050 
```
BTW, `nc` is probably not installed in the target container although not executed if the previous piped commands succeed.

The weirdest thing here is that running the tests at this point, they all pass. Replacing BASH with SH, then the command exits with errorLevel 2:
```
Exit code 2        Misuse of shell builtins (according to Bash documentation)        Example: empty_function() {}
```

@nikolayk812 could you assist me here? Thanks!

**Comment by mdelapenya** [comment]
More on this. If I run the container used in tests:

```
docker run --name nginx --rm -d menedev/delayed-nginx:1.15.2
```
And execute the internal command from my local terminal:

With /bin/bash
```shell
$ docker exec nginx /bin/bash -c "true && (cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :50)"
$ docker exec nginx /bin/bash -c "true && (cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :0050)"
   0: 00000000:0050 00000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 6218691 1 0000000000000000 100 0 0 10 0 
```
With /bin/sh
```shell
$ docker exec nginx /bin/sh -c "true && (cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :50)"  
cat: /proc/net/tcp{,6}: No such file or directory
$ docker exec nginx /bin/sh -c "true && (cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :0050)"
cat: /proc/net/tcp{,6}: No such file or directory
```

I'm going to check how to use /bin/sh properly

**Comment by mdelapenya** [comment]
More on this: trying to escape `awk` quotes properly:

```
$ docker exec nginx /bin/bash -c 'true && (cat /proc/net/tcp6 | awk "\"{print $2}"\" | grep -i :0050)'
$ docker exec nginx /bin/sh -c 'true && (cat /proc/net/tcp{,6} | awk "\"{print $2}"\" | grep -i :0050)' 
cat: /proc/net/tcp{,6}: No such file or directory
```
I see differences in how the `sh` command sees the tcp files.

Entering the container used in tests:

```shell
root@8da5c254bfe3:/# /bin/bash -c 'true && (cat /proc/net/tcp{,6} | awk "\"{print $2}"\" | grep -i :0050)'
   0: 00000000:0050 00000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 6218691 1 0000000000000000 100 0 0 10 0                   
root@8da5c254bfe3:/# echo $?
0
root@8da5c254bfe3:/# /bin/sh -c 'true && (cat /proc/net/tcp{,6} | awk "\"{print $2}"\" | grep -i :0050)'
cat: /proc/net/tcp{,6}: No such file or directory
root@8da5c254bfe3:/# echo $?
1
```
I see slight differences in how the command behaves.

File: wait/host_port.go [hunk 4]
```diff
@@ -109,7 +109,7 @@ func (hp *HostPortStrategy) WaitUntilReady(ctx context.Context, target StrategyT
 
 func buildInternalCheckCommand(internalPort int) string {
 	command := `(
-					cat /proc/net/tcp{,6} | awk '{print $2}' | grep -i :%04x ||
+					cat /proc/net/tcp* | awk '{print $2}' | grep -i :%04x ||
```
Comment (mdelapenya) [inline wait/host_port.go]: That was the clue!! At least, WOMC! Let's 🤞 for Travis :)

**Comment by mdelapenya** [comment]
Tests fixed!

image

**Comment by gianarb** [comment]
Good job!! Thanks @mdelapenya
