### PR TITLE
fix(mssql): bump Docker image version

### LINKED ISSUE #2785: [Bug]: mssql module container crashes
### Testcontainers version

main

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

AMD64

### Go version

go version go1.22.7 linux/amd64

### Docker version

```shell
Unknown in CI
```

### Docker info

```shell
Unknown in CI
```

### What happened?

Container tests fail with an abort

https://github.com/testcontainers/testcontainers-go/actions/runs/10941914684/job/30378453839?pr=2728

### Relevant log output

```shell
2024/09/19 13:38:34 container logs (wait until ready: container exited with code 1):
  SQL Server 2022 will run as non-root by default.
  This container is running as user mssql.
  To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
  This program has encountered a fatal error and cannot continue running at Thu Sep 19 13:38:32 2024
  The following diagnostic information is available:
  
           Reason: 0x00000001
  find: '/proc/9/task/51/fdinfo': Permission denied
  find: '/proc/9/task/52/fdinfo': Permission denied
  find: '/proc/9/task/54/fdinfo': Permission denied
  find: '/proc/9/task/55/fdinfo': Permission denied
  find: '/proc/9/task/56/fdinfo': Permission denied
  find: '/proc/9/task/57/fdinfo': Permission denied
  find: '/proc/9/task/58/fdinfo': Permission denied
  find: '/proc/9/task/59/fdinfo': Permission denied
  find: '/proc/9/task/60/fdinfo': Permission denied
  find: '/proc/9/task/61/fdinfo': Permission denied
  find: '/proc/9/task/64/fdinfo': Permission denied
  find: '/proc/9/task/66/fdinfo': Permission denied
  find: '/proc/9/task/67/fdinfo': Permission denied
  find: '/proc/9/task/68/fdinfo': Permission denied
  find: '/proc/9/task/69/fdinfo': Permission denied
  find: '/proc/9/task/70/fdinfo': Permission denied
  find: '/proc/9/task/71/fdinfo': Permission denied
  find: '/proc/9/task/72/fdinfo': Permission denied
  find: '/proc/9/task/73/fdinfo': Permission denied
  find: '/proc/9/task/75/fdinfo': Permission denied
  find: '/proc/9/task/76/fdinfo': Permission denied
  find: '/proc/9/task/77/fdinfo': Permission denied
  find: '/proc/9/task/78/fdinfo': Permission denied
  find: '/proc/9/task/79/fdinfo': Permission denied
  find: '/proc/9/task/80/fdinfo': Permission denied
  find: '/proc/9/task/81/fdinfo': Permission denied
  find: '/proc/9/task/82/fdinfo': Permission denied
  find: '/proc/9/task/84/fdinfo': Permission denied
  find: '/proc/9/task/85/fdinfo': Permission denied
  find: '/proc/9/task/86/fdinfo': Permission denied
  find: '/proc/9/task/88/fdinfo': Permission denied
  find: '/proc/9/task/89/fdinfo': Permission denied
  find: '/proc/9/task/90/fdinfo': Permission denied
  find: '/proc/9/task/91/fdinfo': Permission denied
  find: '/proc/9/task/92/fdinfo': Permission denied
  find: '/proc/9/task/93/fdinfo': Permission denied
  find: '/proc/9/task/94/fdinfo': Permission denied
  find: '/proc/9/task/97/fdinfo': Permission denied
  find: '/proc/9/task/98/fdinfo': Permission denied
  find: '/proc/9/task/100/fdinfo': Permission denied
  find: '/proc/9/task/101/fdinfo': Permission denied
  find: '/proc/9/task/103/fdinfo': Permission denied
  find: '/proc/9/task/105/fdinfo': Permission denied
  find: '/proc/9/task/106/fdinfo': Permission denied
  find: '/proc/9/task/107/fdinfo': Permission denied
  find: '/proc/9/task/108/fdinfo': Permission denied
  find: '/proc/9/map_files': Permission denied
  find: '/proc/9/fdinfo': Permission denied
  dmesg: read kernel buffer failed: Operation not permitted
  timeout: failed to run command 'journalctl': No such file or directory
  timeout: failed to run command 'journalctl': No such file or directory
  Thu Sep 19 13:38:33 UTC 2024 Capturing program information
  Dump already generated: /var/opt/mssql/log/core.sqlservr.9_19_2024_13_38_32.9, moving to /var/opt/mssql/log/core.sqlservr.9.temp/core.sqlservr.9.gdmp
  Moving logs to /var/opt/mssql/log/core.sqlservr.9.temp/log/paldumper-debug.log
  Thu Sep 19 13:38:33 UTC 2024 Capturing program binaries
  Thu Sep 19 13:38:33 UTC 2024 Not compressing the dump files, moving instead to: /var/opt/mssql/log/core.sqlservr.09_19_2024_13_38_32.9.d
```
```


### Additional information

_No response_

### PR DESCRIPTION
**Pull request by stevenh**
~~Disable all mssql tests as the container is currently crashing, see #2785~~

This PR uses the MSSQL image that does not crash with the current update in the GH workers.

## Related issues
- Relates https://github.com/testcontainers/testcontainers-dotnet/pull/1265
- Relates https://github.com/actions/runner-images/issues/10646
- Relates https://github.com/actions/runner-images/issues/10649
- Closes #2785

### CODE REVIEW

**Comment by stevenh** [comment]
The lint failure is handled by https://github.com/testcontainers/testcontainers-go/pull/2787

**Comment by mdelapenya** [comment]
@stevenh I've updated the PR adding the changes proposed by @HofmeisterAn in the .NET project (thank you!)

File: modules/mssql/mssql_test.go [hunk 1]
```diff
@@ -128,25 +128,3 @@ func TestMSSQLServerWithInvalidPassword(t *testing.T) {
 	testcontainers.CleanupContainer(t, ctr)
 	require.NoError(t, err)
 }
-
```
Comment (mdelapenya) [inline modules/mssql/mssql_test.go:131]: I'm removing this test because it's doing exactly the same as another one, using an image that at the moment has no alternative. We can remove, or skip, whatever you prefer.

**Comment by mdelapenya** [comment]
Tests are passing again! https://github.com/testcontainers/testcontainers-go/actions/runs/10949418982/job/30403422765?pr=2786

**Comment by mdelapenya** [comment]
@stevenh I'm merging this to unblock other PRs. PLMK anything you consider about this. We can discuss in a follow up PR.

Thanks!
