### PR TITLE
fix: don't panic when logs waits for more than 5 seconds

### LINKED ISSUE #606: [Bug]: can not get logs from container which is dead or marked for removal
### Testcontainers version

0.15.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

amd64

### Go Version

1.19

### Docker version

```shell
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:04:24 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:02:38 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.71.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.51GiB
 Name: dev-bgr-test1-lnx7.iv.local
 ID: JCOB:B6QD:MFHY:4B4Y:Z7OA:H7LA:Z5NM:TDOA:7DD7:AMMB:ZBSJ:4KIU
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 34
  Goroutines: 41
  System Time: 2022-11-02T17:54:20.539106249+01:00
  EventsListeners: 0
```

### What happened?

I'm starting a container and waiting for the end of its execution (it is the expected behavior). I also have a log consumer to display what is going on.

```
	c, err := testcontainers.GenericContainer(context.Background(), testcontainers.GenericContainerRequest{
		ContainerRequest: testcontainers.ContainerRequest{
			Image:    image,
			Networks: []string{network},
		},
	})
	if err != nil {
		return err
	}
	defer c.Terminate(context.Background())

	c.FollowOutput(&stdoutLogConsumer{})

	err = c.Start(context.Background())
	if err != nil {
		return err
	}

	err = c.StartLogProducer(context.Background())
	if err != nil {
		return err
	}

	err = wait.ForExit().WithExitTimeout(180*time.Second).WaitUntilReady(context.Background(), c)
	if err != nil {
		return err
	}

	err = c.StopLogProducer()
	if err != nil {
		return err
	}
```

Sometimes the test fails with this error:

```
     | panic: Error response from daemon: can not get logs from container which is dead or marked for removal
     | goroutine 51 [running]:
     | github.com/testcontainers/testcontainers-go.(*DockerContainer).StartLogProducer.func1()
     | 	/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.15.0/docker.go:576 +0x5f6
     | created by github.com/testcontainers/testcontainers-go.(*DockerContainer).StartLogProducer
     | 	/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.15.0/docker.go:558 +0x8a
```

I think there is a problem with the way the log producer is handling a container that terminates: 

```
		r, err := c.provider.client.ContainerLogs(ctx, c.GetContainerID(), options)
		if err != nil {
			// if we can't get the logs, panic, we can't return an error to anything
			// from within this goroutine
			panic(err)
		}
```

I suggest to log a warning and stop log producer instead of calling panic.

### Relevant log output

_No response_

### Additional Information

_No response_

### LINKED ISSUE #946: [Bug]: log producer panics if no logs are produced when using podman
### Testcontainers version

v0.19.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x86_64

### Go version

go1.20

### Docker version

```shell
podman version
Client:       Podman Engine
Version:      4.4.2
API Version:  4.4.2
Go Version:   go1.19.6
Built:        Wed Mar  1 12:22:59 2023
OS/Arch:      linux/amd64
```
```


### Docker info

```shell
podman info:

host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 94.41
    systemPercent: 0.97
    userPercent: 4.62
  cpus: 12
  distribution:
    distribution: fedora
    variant: workstation
    version: "37"
  eventLogger: journald
  hostname: fedora
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.1.18-200.fc37.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1141927936
  memTotal: 33228570624
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.1-1.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.1
      commit: f8a096be060b22ccd3d5f3ebe44108517fbf6c30
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 8272998400
  swapTotal: 8589930496
  uptime: 5h 36m 47.00s (Approximately 0.21 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/martin/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 4
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/martin/.local/share/containers/storage
  graphRootAllocated: 510389125120
  graphRootUsed: 55164096512
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 182
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/martin/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.2
  Built: 1677669779
  BuiltTime: Wed Mar  1 12:22:59 2023
  GitCommit: ""
  GoVersion: go1.19.6
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.2
```

### What happened?

The worker goroutine in DockerContainer.StartLogProducer panics:

```
panic: Get "http://%2Frun%2Fuser%2F1000%2Fpodman%2Fpodman.sock/v1.41/containers/17131d3a1a9090c17437423165cbaf4324140e875b5f69c0ff5c4ee0a78711c5/logs?follow=1&since=1679409204.942642010&stderr=1&stdout=1&tail=": context deadline exceeded

goroutine 66 [running]:
github.com/testcontainers/testcontainers-go.(*DockerContainer).StartLogProducer.func1()
        /home/martin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.19.0/docker.go:604 +0x617
created by github.com/testcontainers/testcontainers-go.(*DockerContainer).StartLogProducer
        /home/martin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.19.0/docker.go:586 +0x8a

```

This is because:
* there is a harcoded 5 second timeout
* `since` parameter is current time
* the container does not produce log output after the since parameter, there are logs only before that time
* `podman` does not return HTTP response headers until some log output is available

So the context deadline expires and the code panics.

It seems that instead of a hardcoded 5 second timeout, the context should be cancelled when the producer is stopped.

Unless this is a bug in podman, in that case we can open a bug report there.

### Relevant log output

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by martin-sucha**
This should fix https://github.com/testcontainers/testcontainers-go/issues/946

## What does this PR do?

This removes panic when logs endpoint takes more than 5 seconds to respond. The panic happened at least with podman when no new logs appear when using follow and since parameters.

We keep retrying until the context is canceled (the retry request would fail anyway) or the producer is stopped, whichever comes first. This makes the retry behavior consistent.

## Why is it important?

Panicking the whole test suite breaks all my tests if the container ends early or there is some temporary error fetching the logs.

## Related issues

- Closes #946
- Closes #606

### CODE REVIEW

**Comment by mdelapenya** [comment]
@martin-sucha thanks for this fix, I was taking a look at #366 yesterday, and they seem related. Could you check if they are overlapping? 🙏

**Comment by martin-sucha** [comment]
@mdelapenya It seems to me that these two PRs are not overlapping. #947 handles retries/removing of the panic and interrupting the HTTP request when context is canceled (internally in the worker goroutine) while #366 handles API changes like only one producer is allowed. I think both should be merged.

It seems there is a small code conflict as both PRs touch the stop channel, but that should be easy to resolve (#366 creates new stop channel each time the method is called and #947 uses a context to handle cancellation inside the worker goroutine, the merged result would create the stop channel each time the method is called and use that to create the context used for cancellation).

**Review by mdelapenya — APPROVED** [review]
I added a comment when reading the stopProducer channel, but apart from that, this PR LGTM. Will wait for your feedback before merging it.

Thank you very much for your time here! 👏

**Comment by mdelapenya** [comment]
@martin-sucha we merged #366, so I think you can continue with this one resolving conflicts 🙏

**Comment by mdelapenya** [comment]
@martin-sucha if you mind, I'm going to fetch this PR and resolve the conflicts myself in top of your commits. Is that ok for you?

File: docker.go [hunk 1]
```diff
@@ -601,6 +601,13 @@ func (c *DockerContainer) CopyToContainer(ctx context.Context, fileContent []byt
 // StartLogProducer will start a concurrent process that will continuously read logs
 // from the container and will send them to each added LogConsumer
 func (c *DockerContainer) StartLogProducer(ctx context.Context) error {
+	ctx, cancel := context.WithCancel(ctx)
+
+	go func() {
+		<-c.stopProducer
```
[the remark this answers is not in the document]
Comment (martin-sucha) [reply docker.go]: Reading from the channel should be enough, now with the changes in main it is even guaranteed that the write will happen once.

**Comment by martin-sucha** [comment]
> @martin-sucha if you mind, I'm going to fetch this PR and resolve the conflicts myself in top of your commits. Is that ok for you?

Sure, no problem.

In the mean time I started signing all my commits, so I've rebased this PR anyway and signed the commit as well.

File: docker.go [hunk 2]
```diff
@@ -634,7 +634,14 @@ func (c *DockerContainer) StartLogProducer(ctx context.Context) error {
 
 	c.stopProducer = make(chan bool)
 
+	ctx, cancel := context.WithCancel(ctx)
+
 	go func(stop <-chan bool) {
+		<-stop
```
Comment (mdelapenya) [inline docker.go:640]: Can you add a little context in this goroutine? IIUC we want to make sure the stopProducer channel's content is read, but I may be wrong. Is this assumption correct?

Comment (martin-sucha) [reply docker.go]: Actually, this is to cancel the context when `c.StopLogProducer()` is called. I've removed the goroutine altogether and added a call to `cancel` directly to `c.StopLogProducer`.

File: docker.go [hunk 3]
```diff
@@ -718,7 +720,8 @@ func (c *DockerContainer) StartLogProducer(ctx context.Context) error {
 // and sending them to each added LogConsumer
 func (c *DockerContainer) StopLogProducer() error {
 	if c.stopProducer != nil {
-		c.stopProducer <- true
+		// Cancel the producer's context.
+		c.stopProducer()
```
Comment (mdelapenya) [inline docker.go:724]: I think there is no `stopProducer()` method at the container level

File: docker.go (hunk 2 above)
Comment (martin-sucha) [reply docker.go]: By the way, should `c.stopProducer` be protected by a mutex? It wasn't protected before so I didn't add the mutex, but I don't see any documentation saying whether the methods can be called concurrently or not.

File: docker.go (hunk 3 above)
Comment (martin-sucha) [reply docker.go:724]: I changed the channel to a CancelFunc in the latest version:
```diff
-       stopProducer      chan bool
+       stopProducer      context.CancelFunc
```

Comment (mdelapenya) [reply docker.go:724]: Oh sorry, I looked at my open IDE instead 🤦

**Review by mdelapenya — APPROVED** [review]

**Comment by mdelapenya** [comment]
@martin-sucha thanks for the fix and your patience while reviewing this PR!

**Comment by mdelapenya** [comment]
Hey @martin-sucha, I'm experimenting certain flakiness in a log_consumer test after this PR has been merged. This is how I am able to reproduce it:

1. Run this command (go test 20 times):
```shell
for x in {1..20}; do go test -timeout 600s -run ^Test_StartStop$ github.com/testcontainers/testcontainers-go -count=1; done
```

No matter if you see log traces about Ryuk being disabled, as I can reproduce it in both cases.

**Expected result**:
```
ok      github.com/testcontainers/testcontainers-go     9.162s
ok      github.com/testcontainers/testcontainers-go     4.312s
ok      github.com/testcontainers/testcontainers-go     9.063s
ok      github.com/testcontainers/testcontainers-go     8.927s
ok      github.com/testcontainers/testcontainers-go     9.050s
ok      github.com/testcontainers/testcontainers-go     9.007s
ok      github.com/testcontainers/testcontainers-go     8.969s
ok      github.com/testcontainers/testcontainers-go     8.995s
ok      github.com/testcontainers/testcontainers-go     9.099s
ok      github.com/testcontainers/testcontainers-go     9.129s
ok      github.com/testcontainers/testcontainers-go     9.008s
ok      github.com/testcontainers/testcontainers-go     8.922s
ok      github.com/testcontainers/testcontainers-go     8.940s
ok      github.com/testcontainers/testcontainers-go     8.970s
ok      github.com/testcontainers/testcontainers-go     8.923s
ok      github.com/testcontainers/testcontainers-go     8.917s
ok      github.com/testcontainers/testcontainers-go     4.187s
ok      github.com/testcontainers/testcontainers-go     8.949s
ok      github.com/testcontainers/testcontainers-go     13.898s
ok      github.com/testcontainers/testcontainers-go     13.711s
```

**Actual result:**
```
Testcontainers properties file has been found: /Users/mdelapenya/.testcontainers.properties
2023/05/02 10:58:52 
**********************************************************************************************
Ryuk has been disabled for the current execution. This can cause unexpected behavior in your environment.
More on this: https://golang.testcontainers.org/features/garbage_collector/
**********************************************************************************************
2023/05/02 10:58:52 
{Host:tcp://127.0.0.1:64666 TLSVerify:0 CertPath: RyukDisabled:true RyukPrivileged:true}
2023/05/02 10:58:52 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 70+testcontainerscloud
  API Version: 1.41
  Operating System: Ubuntu 20.04 LTS
  Total Memory: 7407 MB
2023/05/02 10:58:53 🐳 Creating container for image 
2023/05/02 10:58:54 ✅ Container created: c5a5373cbe84
2023/05/02 10:58:54 🐳 Starting container: c5a5373cbe84
2023/05/02 10:58:54 🚧 Waiting for container id c5a5373cbe84 image: 88762c7f-d78f-4e2f-9f50-7581f2dba603:b46fe4a8-1d54-4c09-9e74-9ac563b13427
2023/05/02 10:58:54 ✅ Container started: c5a5373cbe84
2023/05/02 10:58:55 🐳 Terminating container: c5a5373cbe84
2023/05/02 10:58:55 🚫 Container terminated: c5a5373cbe84
--- FAIL: Test_StartStop (4.00s)
    logconsumer_test.go:247: 
                Error Trace:    /Users/mdelapenya/sourcecode/src/github.com/testcontainers/testcontainers-go/logconsumer_test.go:247
                Error:          Not equal: 
                                expected: []string{"ready\n", "echo mlem\n", "ready\n", "echo mlem\n", "echo mlem2\n"}
                                actual  : []string{"ready\n", "ready\n", "echo mlem\n", "echo mlem2\n"}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,4 +1,3 @@
                                -([]string) (len=5) {
                                +([]string) (len=4) {
                                  (string) (len=6) "ready\n",
                                - (string) (len=10) "echo mlem\n",
                                  (string) (len=6) "ready\n",
                Test:           Test_StartStop
FAIL
FAIL    github.com/testcontainers/testcontainers-go     4.222s
FAIL
Testcontainers properties file has been found: /Users/mdelapenya/.testcontainers.properties
2023/05/02 10:58:56 
**********************************************************************************************
Ryuk has been disabled for the current execution. This can cause unexpected behavior in your environment.
More on this: https://golang.testcontainers.org/features/garbage_collector/
**********************************************************************************************
2023/05/02 10:58:56 
{Host:tcp://127.0.0.1:64666 TLSVerify:0 CertPath: RyukDisabled:true RyukPrivileged:true}
2023/05/02 10:58:56 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 70+testcontainerscloud
  API Version: 1.41
  Operating System: Ubuntu 20.04 LTS
  Total Memory: 7407 MB
2023/05/02 10:58:58 🐳 Creating container for image 
2023/05/02 10:58:58 ✅ Container created: 16a9ba29bc44
2023/05/02 10:58:58 🐳 Starting container: 16a9ba29bc44
2023/05/02 10:58:58 🚧 Waiting for container id 16a9ba29bc44 image: 0bc1cd2f-759c-4b0d-943c-986e23545ba6:8de94fbf-22a8-4ee8-9743-dda25c01f37b
2023/05/02 10:58:59 ✅ Container started: 16a9ba29bc44
2023/05/02 10:59:00 🐳 Terminating container: 16a9ba29bc44
2023/05/02 10:59:00 🚫 Container terminated: 16a9ba29bc44
--- FAIL: Test_StartStop (4.03s)
    logconsumer_test.go:247: 
                Error Trace:    /Users/mdelapenya/sourcecode/src/github.com/testcontainers/testcontainers-go/logconsumer_test.go:247
                Error:          Not equal: 
                                expected: []string{"ready\n", "echo mlem\n", "ready\n", "echo mlem\n", "echo mlem2\n"}
                                actual  : []string{"ready\n", "ready\n", "echo mlem\n", "echo mlem2\n"}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,4 +1,3 @@
                                -([]string) (len=5) {
                                +([]string) (len=4) {
                                  (string) (len=6) "ready\n",
                                - (string) (len=10) "echo mlem\n",
                                  (string) (len=6) "ready\n",
                Test:           Test_StartStop
FAIL
FAIL    github.com/testcontainers/testcontainers-go     4.168s
FAIL
Testcontainers properties file has been found: /Users/mdelapenya/.testcontainers.properties
2023/05/02 10:59:01 
**********************************************************************************************
Ryuk has been disabled for the current execution. This can cause unexpected behavior in your environment.
More on this: https://golang.testcontainers.org/features/garbage_collector/
**********************************************************************************************
2023/05/02 10:59:01 
{Host:tcp://127.0.0.1:64666 TLSVerify:0 CertPath: RyukDisabled:true RyukPrivileged:true}
2023/05/02 10:59:01 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 70+testcontainerscloud
  API Version: 1.41
  Operating System: Ubuntu 20.04 LTS
  Total Memory: 7407 MB
2023/05/02 10:59:03 🐳 Creating container for image 
2023/05/02 10:59:03 ✅ Container created: a78720217309
2023/05/02 10:59:03 🐳 Starting container: a78720217309
2023/05/02 10:59:03 🚧 Waiting for container id a78720217309 image: 740bae7a-6435-40c8-8784-0f8559f006a3:1f80bd5b-c586-4308-90d8-bf7bd593bf0e
2023/05/02 10:59:04 ✅ Container started: a78720217309
2023/05/02 10:59:04 🐳 Terminating container: a78720217309
2023/05/02 10:59:05 🚫 Container terminated: a78720217309
--- FAIL: Test_StartStop (3.97s)
    logconsumer_test.go:247: 
                Error Trace:    /Users/mdelapenya/sourcecode/src/github.com/testcontainers/testcontainers-go/logconsumer_test.go:247
                Error:          Not equal: 
                                expected: []string{"ready\n", "echo mlem\n", "ready\n", "echo mlem\n", "echo mlem2\n"}
                                actual  : []string{"ready\n", "ready\n", "echo mlem\n", "echo mlem2\n"}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,4 +1,3 @@
                                -([]string) (len=5) {
                                +([]string) (len=4) {
                                  (string) (len=6) "ready\n",
                                - (string) (len=10) "echo mlem\n",
                                  (string) (len=6) "ready\n",
                Test:           Test_StartStop
FAIL
FAIL    github.com/testcontainers/testcontainers-go     4.113s
FAIL
Testcontainers properties file has been found: /Users/mdelapenya/.testcontainers.properties
2023/05/02 10:59:05 
**********************************************************************************************
Ryuk has been disabled for the current execution. This can cause unexpected behavior in your environment.
More on this: https://golang.testcontainers.org/features/garbage_collector/
**********************************************************************************************
2023/05/02 10:59:05 
{Host:tcp://127.0.0.1:64666 TLSVerify:0 CertPath: RyukDisabled:true RyukPrivileged:true}
2023/05/02 10:59:06 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 70+testcontainerscloud
  API Version: 1.41
  Operating System: Ubuntu 20.04 LTS
  Total Memory: 7407 MB
2023/05/02 10:59:07 🐳 Creating container for image 
2023/05/02 10:59:07 ✅ Container created: 03601f96cdf6
2023/05/02 10:59:07 🐳 Starting container: 03601f96cdf6
2023/05/02 10:59:08 🚧 Waiting for container id 03601f96cdf6 image: b6a1aa9d-e05c-4dd9-b6e4-80a84c6ccd2f:02499ef0-10ab-4041-9f5c-d23c0c3d26f5
2023/05/02 10:59:08 ✅ Container started: 03601f96cdf6
2023/05/02 10:59:09 🐳 Terminating container: 03601f96cdf6
2023/05/02 10:59:09 🚫 Container terminated: 03601f96cdf6
--- FAIL: Test_StartStop (3.92s)
    logconsumer_test.go:247: 
                Error Trace:    /Users/mdelapenya/sourcecode/src/github.com/testcontainers/testcontainers-go/logconsumer_test.go:247
                Error:          Not equal: 
                                expected: []string{"ready\n", "echo mlem\n", "ready\n", "echo mlem\n", "echo mlem2\n"}
                                actual  : []string{"ready\n", "ready\n", "echo mlem\n", "echo mlem2\n"}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,4 +1,3 @@
                                -([]string) (len=5) {
                                +([]string) (len=4) {
                                  (string) (len=6) "ready\n",
                                - (string) (len=10) "echo mlem\n",
                                  (string) (len=6) "ready\n",
                Test:           Test_StartStop
FAIL
FAIL    github.com/testcontainers/testcontainers-go     4.055s
FAIL
ok      github.com/testcontainers/testcontainers-go     4.136s
Testcontainers properties file has been found: /Users/mdelapenya/.testcontainers.properties
2023/05/02 10:59:14 
**********************************************************************************************
Ryuk has been disabled for the current execution. This can cause unexpected behavior in your environment.
More on this: https://golang.testcontainers.org/features/garbage_collector/
**********************************************************************************************
2023/05/02 10:59:14 
{Host:tcp://127.0.0.1:64666 TLSVerify:0 CertPath: RyukDisabled:true RyukPrivileged:true}
2023/05/02 10:59:15 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 70+testcontainerscloud
  API Version: 1.41
  Operating System: Ubuntu 20.04 LTS
  Total Memory: 7407 MB
2023/05/02 10:59:16 🐳 Creating container for image 
2023/05/02 10:59:16 ✅ Container created: 7458b5cdd330
2023/05/02 10:59:16 🐳 Starting container: 7458b5cdd330
2023/05/02 10:59:17 🚧 Waiting for container id 7458b5cdd330 image: d0cf2a37-6f93-4913-9926-0c37e5705be5:d61714e0-38c3-445c-b58b-2f8b716260ff
2023/05/02 10:59:17 ✅ Container started: 7458b5cdd330
2023/05/02 10:59:18 🐳 Terminating container: 7458b5cdd330
2023/05/02 10:59:18 🚫 Container terminated: 7458b5cdd330
--- FAIL: Test_StartStop (4.05s)
    logconsumer_test.go:247: 
                Error Trace:    /Users/mdelapenya/sourcecode/src/github.com/testcontainers/testcontainers-go/logconsumer_test.go:247
                Error:          Not equal: 
                                expected: []string{"ready\n", "echo mlem\n", "ready\n", "echo mlem\n", "echo mlem2\n"}
                                actual  : []string{"ready\n", "ready\n", "echo mlem\n", "echo mlem2\n"}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,4 +1,3 @@
                                -([]string) (len=5) {
                                +([]string) (len=4) {
                                  (string) (len=6) "ready\n",
                                - (string) (len=10) "echo mlem\n",
                                  (string) (len=6) "ready\n",
                Test:           Test_StartStop
FAIL
FAIL    github.com/testcontainers/testcontainers-go     4.217s
FAIL
Testcontainers properties file has been found: /Users/mdelapenya/.testcontainers.properties
2023/05/02 10:59:19 
**********************************************************************************************
Ryuk has been disabled for the current execution. This can cause unexpected behavior in your environment.
More on this: https://golang.testcontainers.org/features/garbage_collector/
**********************************************************************************************
2023/05/02 10:59:19 
{Host:tcp://127.0.0.1:64666 TLSVerify:0 CertPath: RyukDisabled:true RyukPrivileged:true}
2023/05/02 10:59:19 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 70+testcontainerscloud
  API Version: 1.41
  Operating System: Ubuntu 20.04 LTS
  Total Memory: 7407 MB
2023/05/02 10:59:21 🐳 Creating container for image 
2023/05/02 10:59:21 ✅ Container created: a36e8862b19e
2023/05/02 10:59:21 🐳 Starting container: a36e8862b19e
2023/05/02 10:59:21 🚧 Waiting for container id a36e8862b19e image: 3ecf4857-88a9-404b-9f37-fa9cfef3e393:8353de53-fbd6-470c-a211-123910f3fb2f
2023/05/02 10:59:22 ✅ Container started: a36e8862b19e
2023/05/02 10:59:23 🐳 Terminating container: a36e8862b19e
2023/05/02 10:59:23 🚫 Container terminated: a36e8862b19e
--- FAIL: Test_StartStop (3.93s)
    logconsumer_test.go:247: 
                Error Trace:    /Users/mdelapenya/sourcecode/src/github.com/testcontainers/testcontainers-go/logconsumer_test.go:247
                Error:          Not equal: 
                                expected: []string{"ready\n", "echo mlem\n", "ready\n", "echo mlem\n", "echo mlem2\n"}
                                actual  : []string{"ready\n", "ready\n", "echo mlem\n", "echo mlem2\n"}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,4 +1,3 @@
                                -([]string) (len=5) {
                                +([]string) (len=4) {
                                  (string) (len=6) "ready\n",
                                - (string) (len=10) "echo mlem\n",
                                  (string) (len=6) "ready\n",
                Test:           Test_StartStop
FAIL
FAIL    github.com/testcontainers/testcontainers-go     4.087s
FAIL
ok      github.com/testcontainers/testcontainers-go     4.167s
ok      github.com/testcontainers/testcontainers-go     4.150s
ok      github.com/testcontainers/testcontainers-go     4.099s
ok      github.com/testcontainers/testcontainers-go     3.951s
Testcontainers properties file has been found: /Users/mdelapenya/.testcontainers.properties
2023/05/02 10:59:42 
**********************************************************************************************
Ryuk has been disabled for the current execution. This can cause unexpected behavior in your environment.
More on this: https://golang.testcontainers.org/features/garbage_collector/
**********************************************************************************************
2023/05/02 10:59:42 
{Host:tcp://127.0.0.1:64666 TLSVerify:0 CertPath: RyukDisabled:true RyukPrivileged:true}
2023/05/02 10:59:42 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 70+testcontainerscloud
  API Version: 1.41
  Operating System: Ubuntu 20.04 LTS
  Total Memory: 7407 MB
2023/05/02 10:59:44 🐳 Creating container for image 
2023/05/02 10:59:44 ✅ Container created: bf0fbfe460e8
2023/05/02 10:59:44 🐳 Starting container: bf0fbfe460e8
2023/05/02 10:59:44 🚧 Waiting for container id bf0fbfe460e8 image: 0901522a-517e-417e-b742-e7f69a50465e:d48875d5-6498-4e4e-bbfb-9f75ca9eeeee
2023/05/02 10:59:45 ✅ Container started: bf0fbfe460e8
2023/05/02 10:59:45 🐳 Terminating container: bf0fbfe460e8
2023/05/02 10:59:46 🚫 Container terminated: bf0fbfe460e8
--- FAIL: Test_StartStop (4.05s)
    logconsumer_test.go:247: 
                Error Trace:    /Users/mdelapenya/sourcecode/src/github.com/testcontainers/testcontainers-go/logconsumer_test.go:247
                Error:          Not equal: 
                                expected: []string{"ready\n", "echo mlem\n", "ready\n", "echo mlem\n", "echo mlem2\n"}
                                actual  : []string{"ready\n", "ready\n", "echo mlem\n", "echo mlem2\n"}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,4 +1,3 @@
                                -([]string) (len=5) {
                                +([]string) (len=4) {
                                  (string) (len=6) "ready\n",
                                - (string) (len=10) "echo mlem\n",
                                  (string) (len=6) "ready\n",
                Test:           Test_StartStop
FAIL
FAIL    github.com/testcontainers/testcontainers-go     4.197s
FAIL
ok      github.com/testcontainers/testcontainers-go     4.214s
ok      github.com/testcontainers/testcontainers-go     4.251s
ok      github.com/testcontainers/testcontainers-go     4.209s
Testcontainers properties file has been found: /Users/mdelapenya/.testcontainers.properties
2023/05/02 11:00:00 
**********************************************************************************************
Ryuk has been disabled for the current execution. This can cause unexpected behavior in your environment.
More on this: https://golang.testcontainers.org/features/garbage_collector/
**********************************************************************************************
2023/05/02 11:00:00 
{Host:tcp://127.0.0.1:64666 TLSVerify:0 CertPath: RyukDisabled:true RyukPrivileged:true}
2023/05/02 11:00:01 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 70+testcontainerscloud
  API Version: 1.41
  Operating System: Ubuntu 20.04 LTS
  Total Memory: 7407 MB
2023/05/02 11:00:02 🐳 Creating container for image 
2023/05/02 11:00:02 ✅ Container created: 5f8b2bae342a
2023/05/02 11:00:02 🐳 Starting container: 5f8b2bae342a
2023/05/02 11:00:03 🚧 Waiting for container id 5f8b2bae342a image: dac3b6f1-0c21-4eaf-8451-14cbd7b88db8:0c8fbf43-058c-45ae-ac2d-1b1256d5d81f
2023/05/02 11:00:03 ✅ Container started: 5f8b2bae342a
2023/05/02 11:00:04 🐳 Terminating container: 5f8b2bae342a
2023/05/02 11:00:04 🚫 Container terminated: 5f8b2bae342a
--- FAIL: Test_StartStop (4.18s)
    logconsumer_test.go:247: 
                Error Trace:    /Users/mdelapenya/sourcecode/src/github.com/testcontainers/testcontainers-go/logconsumer_test.go:247
                Error:          Not equal: 
                                expected: []string{"ready\n", "echo mlem\n", "ready\n", "echo mlem\n", "echo mlem2\n"}
                                actual  : []string{"ready\n", "ready\n", "echo mlem\n", "echo mlem2\n"}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,4 +1,3 @@
                                -([]string) (len=5) {
                                +([]string) (len=4) {
                                  (string) (len=6) "ready\n",
                                - (string) (len=10) "echo mlem\n",
                                  (string) (len=6) "ready\n",
                Test:           Test_StartStop
FAIL
FAIL    github.com/testcontainers/testcontainers-go     4.309s
FAIL
Testcontainers properties file has been found: /Users/mdelapenya/.testcontainers.properties
2023/05/02 11:00:05 
**********************************************************************************************
Ryuk has been disabled for the current execution. This can cause unexpected behavior in your environment.
More on this: https://golang.testcontainers.org/features/garbage_collector/
**********************************************************************************************
2023/05/02 11:00:05 
{Host:tcp://127.0.0.1:64666 TLSVerify:0 CertPath: RyukDisabled:true RyukPrivileged:true}
2023/05/02 11:00:05 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 70+testcontainerscloud
  API Version: 1.41
  Operating System: Ubuntu 20.04 LTS
  Total Memory: 7407 MB
2023/05/02 11:00:07 🐳 Creating container for image 
2023/05/02 11:00:07 ✅ Container created: ced0e6d37851
2023/05/02 11:00:07 🐳 Starting container: ced0e6d37851
2023/05/02 11:00:07 🚧 Waiting for container id ced0e6d37851 image: f80b92b6-6379-4a3d-9b94-3773a4ea33da:da819326-5e30-4f9d-bedd-92dedf29cf72
2023/05/02 11:00:08 ✅ Container started: ced0e6d37851
2023/05/02 11:00:09 🐳 Terminating container: ced0e6d37851
2023/05/02 11:00:09 🚫 Container terminated: ced0e6d37851
--- FAIL: Test_StartStop (4.06s)
    logconsumer_test.go:247: 
                Error Trace:    /Users/mdelapenya/sourcecode/src/github.com/testcontainers/testcontainers-go/logconsumer_test.go:247
                Error:          Not equal: 
                                expected: []string{"ready\n", "echo mlem\n", "ready\n", "echo mlem\n", "echo mlem2\n"}
                                actual  : []string{"ready\n", "ready\n", "echo mlem\n", "echo mlem2\n"}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,4 +1,3 @@
                                -([]string) (len=5) {
                                +([]string) (len=4) {
                                  (string) (len=6) "ready\n",
                                - (string) (len=10) "echo mlem\n",
                                  (string) (len=6) "ready\n",
                Test:           Test_StartStop
FAIL
FAIL    github.com/testcontainers/testcontainers-go     4.203s
FAIL
ok      github.com/testcontainers/testcontainers-go     4.359s
ok      github.com/testcontainers/testcontainers-go     4.083s
ok      github.com/testcontainers/testcontainers-go     4.390s
```

I'm tempted to revert the commit and give the chance to debug this, so that we can perform a new release, but I wanted to check with you first.

**Comment by mdelapenya** [comment]
@martin-sucha I think I have a clue on what's going on: the test does the assertions and because we changed here how the log producers behave, it's very likely that the messages are not there yet at test time.

If you take a look at https://github.com/testcontainers/testcontainers-go/pull/947/files#diff-b68159b6168f099a639e8c6f96d75f23333ab0f0505ee22a98268748db17ae4cR635-R637, we are removing the channel that was used to receive the signal that the log producer was stopped. Therefore, we are only waiting for the Done method of the context: https://github.com/testcontainers/testcontainers-go/pull/947/files#diff-b68159b6168f099a639e8c6f96d75f23333ab0f0505ee22a98268748db17ae4cR663

Those are my initial suspects, but it's not easy to debug. Wdyt, anything on the top of your head?

**Comment by martin-sucha** [comment]
@mdelapenya I've finally looked at the issue and it seems to me that the failing test was wrong: it did not wait for the log lines to appear. Please see https://github.com/testcontainers/testcontainers-go/pull/1278
