### PR TITLE
fix(postgres): snapshot restore

### LINKED ISSUE #3263: [Bug]: Multiple errors by PostgreSQL snapshot restore
### Testcontainers version

v0.38.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux, macOS

### Host arch

x86_64, arm64

### Go version

1.24.4

### Docker version

```shell
Client:
 Version:           28.3.2
 API version:       1.51
 Go version:        go1.24.5
 Git commit:        578ccf6
 Built:             Wed Jul  9 16:12:57 2025
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.43.2 (199162)
 Engine:
  Version:          28.3.2
  API version:      1.51 (minimum version 1.24)
  Go version:       go1.24.5
  Git commit:       e77ff99
  Built:            Wed Jul  9 16:13:56 2025
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.27
  GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Version:    28.3.2
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  ai: Docker AI Agent - Ask Gordon (Docker Inc.)
    Version:  v1.9.11
    Path:     $HOME/.docker/cli-plugins/docker-ai
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.26.1-desktop.1
    Path:     $HOME/.docker/cli-plugins/docker-buildx
  cloud: Docker Cloud (Docker Inc.)
    Version:  v0.4.18
    Path:     $HOME/.docker/cli-plugins/docker-cloud
  compose: Docker Compose (Docker Inc.)
    Version:  v2.39.1-desktop.1
    Path:     $HOME/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.42
    Path:     $HOME/.docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Docker Inc.)
    Version:  v0.2.0
    Path:     $HOME/.docker/cli-plugins/docker-desktop
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.29
    Path:     $HOME/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.4.0
    Path:     $HOME/.docker/cli-plugins/docker-init
  mcp: Docker MCP Plugin (Docker Inc.)
    Version:  v0.13.0
    Path:     $HOME.docker/cli-plugins/docker-mcp
  model: Docker Model Runner (EXPERIMENTAL) (Docker Inc.)
    Version:  v0.1.36
    Path:     $HOME/.docker/cli-plugins/docker-model
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     $HOME.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.18.2
    Path:     $HOME/.docker/cli-plugins/docker-scout

Server:
 Containers: 17
  Running: 6
  Paused: 0
  Stopped: 11
 Images: 16
 Server Version: 28.3.2
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Discovered Devices:
  cdi: docker.com/gpu=webgpu
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.10.14-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 12
 Total Memory: 7.653GiB
 Name: docker-desktop
 ID: 4b765a04-c404-46ae-a91e-8b3592d017b9
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix://$HOME/Library/Containers/com.docker.docker/Data/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: DOCKER_INSECURE_NO_IPTABLES_RAW is set
```

### What happened?

Motivated by #3233 I was trying the workaround as I have this error as well.

However, I experience two other errors with `postgres.Restore(...)` frequently:
- `failed to restore database snapshot: could not execute restore command CREATE DATABASE "xxx" WITH TEMPLATE "snapshot-4d3fddf7-ff41-47b9-acee-7f9a534b88ca" OWNER "xxx": pq: source database "snapshot-4d3fddf7-ff41-47b9-acee-7f9a534b88ca" is being accessed by other users`
- `failed to restore database snapshot: could not execute restore command DROP DATABASE "xxx" with (FORCE): pq: database "xxx" does not exist`

We have about ~100 integration tests in our project which are based on test containers (many of them with PostgreSQL).

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ascheman**
Label: Bug

## What does this PR do?

It fixes #3263 by providing two changes
- Close any existing connection on the snapshot DB
- Drop the database only if it exists

## Why is it important?

We had very flaky tests without this change.

## Related issues

Seldomly, we still run into #3233 and would be happy about a fix as well.

- Closes #3263
- Relates #3233

## How to test this PR

As the error(s) only occur in some unknown circumstances it is very hard to enforce their occurrence and also a test situation where they fire.

### CODE REVIEW

File: modules/postgres/postgres.go [hunk 1]
```diff
@@ -295,8 +295,10 @@ func (c *PostgresContainer) Restore(ctx context.Context, opts ...SnapshotOption)
 
 	// execute the commands to restore the snapshot, in order
 	return c.execCommandsSQL(ctx,
-		// Drop the entire database by connecting to the postgres global database
-		fmt.Sprintf(`DROP DATABASE "%s" with (FORCE)`, c.dbName),
+		// Terminate all connections to the template database
+		fmt.Sprintf(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = '%s' AND pid <> pg_backend_pid()`, snapshotName),
```
Comment (stevenh) [inline modules/postgres/postgres.go:300]: question: Based on [the docs](https://www.postgresql.org/docs/current/sql-dropdatabase.html) FORCE already does the connection termination?

Comment (ascheman) [reply modules/postgres/postgres.go:300]: > question: Based on [the docs](https://www.postgresql.org/docs/current/sql-dropdatabase.html) FORCE already does the connection termination?

Well, the docs list some exceptions. In our experience 20% of the failures were due to the respective first error in #3263. We could drastically reduce failure rate by this change (only happened once in my latest 30 test runs with ~100 test cases each). Perhaps it is a problem in PostgreSQL (though they claim some exceptions)? Nevertheless, we have have to cope with it anyway.

Comment (stevenh) [reply modules/postgres/postgres.go:300]: Thanks for the clarification, can we add a comment to that effect so future us knows this is the case.

Comment (ascheman) [reply modules/postgres/postgres.go:300]: Done
