### PR TITLE
bug: allow start container with reuse in different test package

### LINKED ISSUE #1277: [Bug]: Reuse ignores WaitingFor in container request
### Testcontainers version

v0.20.1

### Using the latest Testcontainers version?

Yes

### Host OS

OS X

### Host arch

x86

### Go version

1.20.4

### Docker version

```shell
Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.10.2)
  extension: Manages Docker extensions (Docker Inc., v0.2.9)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.19.0)

Server:
 Containers: 7
  Running: 1
  Paused: 0
  Stopped: 6
 Images: 24
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.124-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.64GiB
 Name: docker-desktop
 ID: NXUF:QSFY:ZCSL:ZGGF:MKTL:RTCA:OTKI:BUR6:PZWE:C654:Z4C4:NJBH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

Running test suites for multiple packages (go test ./...) that use a kafka container started using testcontainers with Reuse enabled. Only the first test called actually waits for the WaitingFor conditions, the other processes skip waiting for and start executing before the container is ready (is running but services on the container aren't up).

### Relevant log output

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Alviner**
## What does this PR do?

When creating reusable container from different test binaries in parallel, you can get "name conflict" from docker daemon, because different binaries don't have a shared mutex

Instead of exiting with error when receiving "name conflict", we will try to wait for the container creation to complete using the ContainerList method and call ready/started hooks after.

## Why is it important?
This PR allows a reusable container to be used in parallel test binaries run from the "go test ./..." command.

## Related issues

- Closes #1277
- Closes #1572 
- Relates #809

### CODE REVIEW

**Comment by Alviner** [comment]
@mdelapenya Hi! Please take a look, I encountered the same issue, refreshed the code from #1572

File: docker.go [hunk 1]
```diff
@@ -1187,7 +1224,24 @@ func (p *DockerProvider) ReuseOrCreateContainer(ctx context.Context, req Contain
 		terminationSignal:   termSignal,
 		stopLogProductionCh: nil,
 		logger:              p.Logger,
-		isRunning:           c.State == "running",
+		lifecycleHooks: []ContainerLifecycleHooks{
+			{
+				PostStarts:  allHooks.PostStarts,
+				PostReadies: allHooks.PostReadies,
```
[the remark this answers is not in the document]
Comment (Alviner) [reply docker.go:1230]: let's add all of them, but not all of them will be executed, because this flow doesn't have all steps like with creation one. Does it acceptable?

File: docker.go [hunk 2]
```diff
@@ -1178,6 +1208,13 @@ func (p *DockerProvider) ReuseOrCreateContainer(ctx context.Context, req Contain
 		}
 	}
 
+	// default hooks include logger hook and pre-create hook
```
[the remark this answers is not in the document]
Comment (mdelapenya) [reply docker.go:1211]: Yeah, let's not add the copy file hook. I think it's not need when reused

**Comment by Alviner** [comment]
@mdelapenya Are there some flaky tests? I just successfully flew the checks in my fork)

https://github.com/Alviner/testcontainers-go/actions/runs/7993042944/

**Review by mdelapenya — APPROVED** [review]
LGTM, thanks!

Just to let you know, we are thinking about revamping how the reusable containers work, in a more consistent and deterministic manner. So this code could change or be removed. But until that, this is perfectly fine, thanks for your time contributing it!

**Comment by mdelapenya** [comment]
BTW I'm renaming the PR to bug, as this is fixing the existing behaviour.

File: docker.go [hunk 3]
```diff
@@ -1178,6 +1208,13 @@ func (p *DockerProvider) ReuseOrCreateContainer(ctx context.Context, req Contain
...
+	defaultHooks := []ContainerLifecycleHooks{
+		DefaultLoggingHook(p.Logger),
+		defaultReadinessHook(),
```
Comment (mdonkers) [inline docker.go:1214]: Question @Alviner / @mdelapenya : is there any good reason why the `defaultReadinessHook()` should be added _also_ for a container being reused?

Reason I'm asking is that I noticed quite some overhead when changing testcontainers from `v0.28.0` to `v0.29.1` and was able to 'bisect' the issue to this PR.

As we're heavily relying on reused containers, this overhead is quite noticeable:
```
$ time make integration-test
...
real	0m4.555s
user	0m10.373s
sys	0m1.093s
```
before. Opposed to now:
```
real	0m9.177s
user	0m8.254s
sys	0m1.094s
```

When the container is initially created (and due to the mutex) it should have been fully started and the 'readiness' state was already checked. So from my perspective I don't see a reason to keep checking this.

Comment (Alviner) [reply docker.go:1214]: > Question @Alviner / @mdelapenya : is there any good reason why the `defaultReadinessHook()` should be added _also_ for a container being reused?
> 
> Reason I'm asking is that I noticed quite some overhead when changing testcontainers from `v0.28.0` to `v0.29.1` and was able to 'bisect' the issue to this PR.
> 
> As we're heavily relying on reused containers, this overhead is quite noticeable:
> 
> ```
> $ time make integration-test
> ...
> real	0m4.555s
> user	0m10.373s
> sys	0m1.093s
> ```
> 
> before. Opposed to now:
> 
> ```
> real	0m9.177s
> user	0m8.254s
> sys	0m1.094s
> ```
> 
> When the container is initially created (and due to the mutex) it should have been fully started and the 'readiness' state was already checked. So from my perspective I don't see a reason to keep checking this.

When you run tests from different packages, they run in separate processes with a single common parent. Therefore, if you reuse containers in these packages, you need to wait for the readiness hook, which effectively triggers waitFor in most situations.

Comment (mdonkers) [reply docker.go:1214]: Right, ok. Then the [mutex](https://github.com/testcontainers/testcontainers-go/blob/09648d156cd13a650925f423768c5ee7b1f72734/generic.go#L68) would of course no longer guarantee readiness of the Container.

But then I do think a solution for another bug I found (https://github.com/testcontainers/testcontainers-go/issues/2445) might resolve it to some extend. Because if there's a way to (explicitly) 'scope' a reusable container to the SessionID, then it's guaranteed its also always the same mutex instance. But I'm waiting for some feedback there to do a PR :-)

Comment (mdelapenya) [reply docker.go:1214]: Thank you all for bringing this topic, and for being so proactive in the discussion 🙇 

We are working in a better reusable experience for testcontainers-go. At the moment, it was initially built as an experimental feature that was immediately used when landed, so now it's part of the public API 😅 so difficult to remove without causing trouble to users.

The new experience will be improved and more robust and provided through Testcontainers Desktop.

Comment (mdonkers) [reply docker.go:1214]: Thx for the additional insight.
But does that mean no changes are expected or even approved just for the library? I don't think it needs to be removed, but there must be a way to both fix the existing behaviour and not break others...
I surely hope it would not require using the TestContainers desktop app since that would not work in our CI pipeline. And currently the "reuse" flag is causing actual issues: https://github.com/testcontainers/testcontainers-go/issues/2445#issuecomment-2016773569
